### ISSUE TITLE
Update Mocha to 8.3.0

### ISSUE THREAD

**Issue by hobovsky** [codewars/runner#105]
- Name: Mocha
- Version: 8.3.0
- Release Note/Changelog: https://github.com/mochajs/mocha/releases/tag/v8.3.0

This version fixes a [bug](https://github.com/mochajs/mocha/pull/4112) which affects some kata returning bigint.

There was an idea for a [snippet](https://github.com/codewars/docs/issues/257) serving as a workaround for the issue, but maybe just updating the library would be better.

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
Deployed
