### ISSUE TITLE
Add Julia v1.5.3

### ISSUE THREAD

**Issue by XRFXLP** [codewars/runner#106]
Existing version of Julia is nearly 2.5 year old, 
Please complete the following information:

- Julia
- 1.5.3
- Release Note: [Julia v1.5 Release Notes](https://docs.julialang.org/en/v1/NEWS/#Julia-v1.5-Release-Notes)
---

:+1: reaction _might_ help to get this request prioritised.

**Comment by kazk** [comment]
Any requests for commonly used packages? I'll add IterTools (#36).

**Comment by XRFXLP** [comment]
Thanks.

Here are couple of them 
 - [DataStructures.jl](https://juliapackages.com/p/datastructures)
Implements common data structures like `collections` of python.
- [Lazy.jl](https://juliapackages.com/p/lazy)
Implements some functional programming utilities.

**Comment by kazk** [comment]
Deployed. Running a job to update compatible ones right now.
I've installed the packages, but haven't confirmed using it. I don't know any Julia, so please test them and let me know.
