### ISSUE TITLE
Add float_eq for Rust

### ISSUE THREAD

**Issue by imjasonmiller** [codewars/runner#107]
Please complete the following information about the package:

- Package name: [`float_eq`](https://docs.rs/float_eq/0.5.0/float_eq/)
- Language name: Rust
- Website: https://github.com/jtempest/float_eq-rs

Following are optional, but will help us consider adding:

- Why is this useful?
  In response to https://github.com/codewars/docs/issues/242#issuecomment-782469126, this crate provides authors with assertions that check if a floating point answer meets a given threshold. This will prevent authors from having to implement their own implementation, possibly leading to common mistakes.
 
   This crate offers a [detailed documentation](https://docs.rs/float_eq/0.5.0/float_eq/) and is actively maintained. The end user can also combine comparisons:
 
   * [Absolute epsilon comparison](https://docs.rs/float_eq/0.5.0/float_eq/#absolute-epsilon-comparison)
   * [Relative epsilon comparison](https://docs.rs/float_eq/0.5.0/float_eq/#relative-epsilon-comparison)
   * [Units in the Last Place (ULPs) comparison](https://docs.rs/float_eq/0.5.0/float_eq/#units-in-the-last-place-ulps-comparison)
 
- Example Code:

  ```rust
  use float_eq::assert_float_eq;

  let x: f32 = 4.0;
  let y: f32 = 2.0;

  assert_float_eq!(x, y, abs <= 2.0); // Absolute comparison
  assert_float_eq!(x, y, rmax <= 0.50); // Relative comparison
  assert_float_eq!(x, y, ulps <= 8388608); // Units in the Last Place comparison
  ```

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
Deployed.

The following have something matching `assert_fuzzy` in tests:

1. [Braking well](https://www.codewars.com/kata/565c0fa6e3a7d39dee000125/rust)
1. [Euler's method for a first-order ODE](https://www.codewars.com/kata/56347fcfd086de8f11000014/rust)
1. [Floating-point Approximation (I)](https://www.codewars.com/kata/58184387d14fc32f2b0012b2/rust)
1. [Floating-point Approximation (III)](https://www.codewars.com/kata/5b0c0ec907756ffcff00006e/rust)
1. [Going to zero or to infinity?](https://www.codewars.com/kata/55a29405bc7d2efaff00007c/rust)
1. [Magnet particules in boxes](https://www.codewars.com/kata/56c04261c3fcf33f2d000534/rust)
1. [Parabolic Arc Length](https://www.codewars.com/kata/562e274ceca15ca6e70000d3/rust)
1. [Positions Average](https://www.codewars.com/kata/59f4a0acbee84576800000af/rust)
1. [Probabilities for Sums in Rolling  Cubic Dice](https://www.codewars.com/kata/56f78a42f749ba513b00037f/rust)
1. [Rainfall](https://www.codewars.com/kata/56a32dd6e4f4748cc3000006/rust)
1. [Robinson Crusoe](https://www.codewars.com/kata/5d95b7644a336600271f52ba/rust)
1. [Simpson's Rule - Approximate Integration](https://www.codewars.com/kata/565abd876ed46506d600000d/rust)
1. [Which x for that sum?](https://www.codewars.com/kata/5b1cd19fcd206af728000056/rust)

If you know any other functions/macros used that should be replaced, let me know. I'll update the wiki page as well.
