### ISSUE TITLE
Add PostgreSQL 13

### ISSUE THREAD

**Issue by FArekkusu** [codewars/runner#11]
Postgres has been steadily improving over the years, and the latest release has brought a couple interesting features, so it would be nice to have version 13.* available on CW.

- Name: PostgreSQL
- Version: 13.0
- Release Note/Changelog: https://www.postgresql.org/docs/release/13.0/

---

:+1: reaction _might_ help.

**Comment by kazk** [comment]
Added Postgres 13 as a new language version for SQL kata. I haven't run the script to enable them on existing kata yet.

I updated the test helper and extracted to https://github.com/codewars/sql_spec_helper (setup described on README is already done for you on Codewars, so you don't need to do anything to use it). I tried to minimize breaking changes, but there are some.
