### ISSUE TITLE
Add Crystal 1.0.0

### ISSUE THREAD

**Issue by Iwaslazkis** [codewars/runner#112]
Please complete the following information:

- Name: Crystal
- Version: 1.0.0
- Release Note/Changelog: https://github.com/crystal-lang/crystal/releases/tag/1.0.0

This version onwards is **stable** and promises **no breaking changes** *(at least until 2.0)*, so it's a great time to upgrade the current 3-year-old 0.24.2 version.

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
> it's a great time to upgrade the current 3-year-old 0.24.2 version.

0.34 has been supported. Some kata needs to be updated though https://github.com/codewars/content-issues/wiki/List-of-Crystal-Kata-to-Update

**Comment by Iwaslazkis** [comment]
Oh I see, awesome! I got that [0.24.2 statement from the codewars.com/wiki on Crystal](https://github.com/codewars/codewars.com/wiki/Language-Crystal), I just updated it (never contributed to a wiki; I don't know if it was supposed to just *save* my changes without a PR or anything). I'll also be seeing if I can help with those Kata updates later, thanks!

It's less urgent then, being only 3 versions behind, but I still think updating to 1.0.0 might be worth however as it is the first stable version. There a handful of breaking changes since.

**Comment by kazk** [comment]
Thanks for updating the wiki. Anyone with GitHub account is allowed to contribute at the moment. We do get notification, and it's easy to revert, so we haven't had any serious issues. We're still working on the new documentation.

> I still think updating to 1.0.0 might be worth however as it is the first stable version. There a handful of breaking changes since.

Yeah, I'd like to add 1.0 soon because users expect that now. The stability guarantee helps keeping up as well.

**Comment by kazk** [comment]
Deployed and updated compatible kata. 107 are incompatible: https://github.com/codewars/content-issues/wiki/List-of-Crystal-Kata-to-Update
