### ISSUE TITLE
Add Rust 1.51

### ISSUE THREAD

**Issue by poly000** [codewars/runner#120]
Please complete the following information:

- Name: Rust
- Version: 1.51
- Release Note/Changelog: https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
1.52 will be released in a few weeks, so I'm planning to add that soon after.

I can't add a new Rust version every 6 weeks, but I do want a recent version supported. So, I'm thinking of adding evens for now.

**Comment by imjasonmiller** [comment]
> I can't add a new Rust version every 6 weeks

I was holding off on raising an issue for an updated Rust version for that exact reason, but 1.52 was just released! 🎉

**Comment by kazk** [comment]
Superseded by #121
