### ISSUE TITLE
Add PowerShell 7.1.3

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/runner#122]
Please complete the following information:

- Name: PowerShell
- Version: 7.1.3
- Release Note/Changelog: https://github.com/PowerShell/PowerShell/blob/master/CHANGELOG/7.1.md#713---2021-03-11

The current supported version 6.0.0 was released back in January 2018 which is over three years ago at the time of writing.

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
Closing as a duplicate of #96.
