### ISSUE TITLE
Add Racket 8.1

### ISSUE THREAD

**Issue by s-cerevisiae** [codewars/runner#127]
Please complete the following information:

- Name: Racket 
- Version: 8.1
- Release Note/Changelog: https://blog.racket-lang.org/2021/05/racket-v8-1.html

It has been more than 2 years since the release of currently supported version (Racket 7.2), and Racket CS has been stabilized during this time.

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
@s-cerevisiae Could you check if https://github.com/codewars/codewars-rackunit still works without any errors/warnings on Racket 8.1? After installing, try some tests like:

`tests.rkt`
```racket
#lang racket

(require "solution.rkt")
(require rackunit codewars/rackunit)

(run-tests
  (test-suite
    "example"
    (test-case "add" (check-equal? (add 1 1) 2))))
```
`solution.rkt`
```racket
#lang racket
(provide add)

(define (add a b) (+ a b))
```

```bash
racket tests.rkt
```

This will save me some time. If not, don't worry, I'll try it myself when I can.

**Comment by s-cerevisiae** [comment]
@kazk It works.
output:
```
<DESCRIBE::>example

<IT::>add

<PASSED::>Test Passed

<COMPLETEDIN::>

<COMPLETEDIN::>
```

**Comment by kazk** [comment]
Deployed and updated compatible kata to 8.1.

**Comment by Voileexperiments** [comment]
@kazk For some reasons operations with big number seem to be *extremely* slow in Racket 8.1 comparing to Racket 7.2, which is affecting two katas. I think it should be resolved first since it'll affect all the algorithm katas.

**Comment by kazk** [comment]
The only difference between the two (other than Racket) is the base image. 7.1 uses Ubuntu Bionic (18.04) based, 8.1 uses Focal (20.04). I can try 8.1 with Bionic and see if it's better.

Diff 7.2 to 8.1:
```diff
-FROM buildpack-deps:bionic-scm AS builder
+FROM buildpack-deps:20.04-scm AS builder

 RUN set -ex; \
     mkdir -p /opt/racket; \
-    wget -qO /tmp/racket.sh https://mirror.racket-lang.org/installers/7.2/racket-minimal-7.2-x86_64-linux-natipkg.sh; \
+    wget -qO /tmp/racket.sh https://mirror.racket-lang.org/installers/8.1/racket-minimal-8.1-x86_64-linux-natipkg.sh; \
     echo "yes\n1\n" | sh /tmp/racket.sh --unix-style --dest /opt/racket --create-dir; \
     rm /tmp/racket.sh;
 ENV PATH=/opt/racket/bin:$PATH
 RUN set -ex; \
     raco setup; \
     raco pkg config --set catalogs \
-      "https://download.racket-lang.org/releases/7.2/catalog/" \
+      "https://download.racket-lang.org/releases/8.1/catalog/" \
       "https://pkg-build.racket-lang.org/server/built/catalog/" \
       "https://pkgs.racket-lang.org" \
       "https://planet-compats.racket-lang.org" \
     ; \
     raco pkg install --scope installation --auto rackunit-lib; \
-    raco pkg install --scope installation --auto https://github.com/Codewars/codewars-rackunit.git; \
+    raco pkg install --scope installation --auto https://github.com/codewars/codewars-rackunit.git; \
     raco pkg install --scope installation --auto typed-racket-lib;

-FROM ubuntu:18.04
+FROM ubuntu:20.04
 RUN set -ex; \
     useradd --create-home -u 9999 codewarrior; \
     mkdir -p /workspace/racket; \
```

**Comment by kazk** [comment]
Same result with 8.1 on Bionic.

**Comment by kazk** [comment]
I just installed Racket 8.1 on my laptop, and the millionth fibonacci takes 14s. So, this isn't Code Runner or Docker.

**Comment by kazk** [comment]
Opened #129 to keep track of the performance issue. Please let me know if you find anything.
