### ISSUE TITLE
Add Perl

### ISSUE THREAD

**Issue by suic86** [codewars/runner#13]
Please complete the following information about the language:

- Name: Perl
- Website: [Perl](perl.org)
- Language Version: Perl 5.28.x or later

The following are optional, but will help us add the language:

- Test Frameworks:
    - [Test2](https://metacpan.org/pod/Test2)
        - source: https://github.com/Test-More/test-more
        - has custom formatter support
        - [Test2:Suite](https://metacpan.org/pod/Test2::Suite)
        - [JUnit Renderer](https://github.com/cpanel/Test2-Harness-Renderer-JUnit/blob/master/lib/Test2/Harness/Renderer/JUnit.pm)
    - ~~[Test::More](https://metacpan.org/pod/Test::More)~~ recommends `Test2::Suite`
    - ~~[Test::Unit](https://metacpan.org/pod/Test::Unit)~~ abandoned?
- How to install: with [cpan command](https://perldoc.perl.org/CPAN.html) or [cpanminus](https://metacpan.org/pod/App::cpanminus)
- How to compile/run: Is described by each framework
- Any comments: Good candidate for text manipulation, regexp and code-golfing and esoteric/domain specific language kata (see [here](https://fosdem.org/2019/schedule/event/perl6newtool/)). It's also a pity that there's Python, Ruby, JS support but not Perl support. :)

---

**Progress:**

- [x] Run
- [x] Test
- [x] Output
---

:+1: reaction _might_ help.

**Comment by kazk** [comment]
Deployed
