### ISSUE TITLE
Add Erlang OTP 26

### ISSUE THREAD

**Issue by MobulaKuhlii** [codewars/runner#134]
Please complete the following information:

- Name: Erlang OTP
- Version: 24.0
- Release Note/Changelog: https://www.erlang.org/news/148

Current version `20` is quite outdated

Most significant change is this:
> The BeamAsm JIT-compiler has been added to Erlang/OTP and will give a significant performance boost for many applications.
The JIT-compiler is enabled by default on most x86 64-bit platforms that have a C++ compiler that can compile C++17.
To verify that a JIT enabled emulator is running you can use erlang:system_info(emu_flavor).

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
Added Erlang OTP 26. All published kata were updated to use it by default.
