### ISSUE TITLE
Add junit-jupiter-params for Java

### ISSUE THREAD

**Issue by hobovsky** [codewars/runner#135]
### General info

- Package name: `junit-jupiter-params`
- Language name: Java
- Website: `https://junit.org/junit5/`

###  Why is this useful? 

It provides a way to create parametrized tests with JUnit 5

### Example Code:

https://www.baeldung.com/parameterized-tests-junit-5#6-method
https://www.petrikainulainen.net/programming/testing/junit-5-tutorial-writing-parameterized-tests/

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
Deployed. I've only tested the basics, so let me know if you find something weird.

**Comment by hobovsky** [comment]
I managed to use it in a translation in a way I more or less intended: https://www.codewars.com/kumite/5f27d39d3ec3ea00247dd917?sel=610927453c76bb0032bac272

It works nice, test output is also nice. Thanks a lot.

**Comment by Madjosz** [comment]
### Proposal for a new translation/kumite test template using JUnit 5

    import org.junit.jupiter.api.Test;
    import static org.junit.jupiter.api.Assertions.assertEquals;
    
    // TODO: Replace examples and use TDD by writing your own tests
    
    class SolutionTest {
        @Test
        void testSomething() {
            // assertEquals("expected", "actual");
        }
    }

### Proposal for the "insert example" test code in "new kata" editor

    import org.junit.jupiter.api.Test;
    import static org.junit.jupiter.api.Assertions.assertEquals;
    
    class PersonTest {
        @Test
        void testGreet() {
            Person shoki = new Person("Shoki, the Demon Queller");
            assertEquals("Konbanwa!  My name is Shoki, the Demon Queller.  It is nice to meet you, Sun Wukong, the Monkey King!",
                                 shoki.greet("Sun Wukong, the Monkey King"));
        }
    }

### Changes

* replace `org.junit.Test` by `org.junit.jupiter.api.Test`
* replace `org.junit.Assert` by `org.junit.jupiter.api.Assertions`
* remove `org.junit.runners.JUnit4`
* change class and method visibility from `public` to package private

**Comment by kazk** [comment]
Updated the template. Thanks.
