### ISSUE TITLE
Julia `show` and `display` does not append new line

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/runner#137]
When I try something like

```julia
  display(1)
  display(2)
  display(3)
```

I get `123` in the log instead of 3 lines of `1`, `2` and `3`. I don't think this is expected.

**Comment by XRFXLP** [comment]
Julia's `display`'s behaviour depends a lot on the environment from it is evoked:
 
I believe you're comparing two different things hence finding something which you'd not expected

In normal source compilation: 
![image](https://user-images.githubusercontent.com/23459568/127469375-5b869b08-b3f9-4816-b865-d01b388bb572.png)

(which is exactly as you shown)

But in REPL:
![image](https://user-images.githubusercontent.com/23459568/127470107-f8b4cbfa-38f2-4dc3-919f-1b4eb89703ca.png)
(it appends newline, just like `println`)
