### ISSUE TITLE
Add Raku

### ISSUE THREAD

**Issue by suic86** [codewars/runner#14]
Please complete the following information about the language:

- Name: Raku
- Website: https://raku.org/
- Language Version: [Rakudo Star 2020.01 or later](https://rakudo.org/files/)

The following are optional, but will help us add the language:

- Test Frameworks:
    - [integrated testing framework](https://docs.perl6.org/language/testing)
        - simple TAP
    - ~~[PSpec i.e. RSpec for Perl 6](https://github.com/supernovus/PSpec)~~
    - https://github.com/perl6-community-modules/perl6-Testo
        - custom output
- How to install: [Perl 6 download](https://perl6.org/downloads/)

---

**Progress:**

- [x] Run
- [x] Test
- [x] Output

---

:+1: reaction _might_ help.

**Comment by kazk** [comment]
Raku will be supported with the standard Test module. I wrote [codewars/raku-tap2codewars][tap2codewars] so we can do:

```bash
$ raku 2>&1 t/tests.t | tap2codewars
```
to get the output we need.
This should work for Perl as well.

[tap2codewars]: https://github.com/codewars/raku-tap2codewars

**Comment by suic86** [comment]
@kazk: I've created a [raku translation](https://www.codewars.com/kumite/5f8f590c63c8dc002360c602?sel=5f8f590c63c8dc002360c602) to test the new runner. It works well. Thanks!

However, using `say` in tests or in solution code corrupts the test output. IMO, this is a bug, as printing the input is a common debugging technique.

**Comment by kazk** [comment]
>  IMO, this is a bug, as printing the input is a common debugging technique.

TAP uses both stdout and stderr (for diagnostics) so outputs can mess with them. I'm using the official parser and any unrecognized line should be parsed as `Unknown` and reported as is.

Can you open a new issue at https://github.com/codewars/raku-tap2codewars with example code? It might be something that can be fixed by changing how test failures are currently reported.

**Comment by kazk** [comment]
Hmm, weird. It only happens when there's more than one test case.

So
```text
foo
    ok 1 -
    1..1
ok 1 - tests
1..1
```
works, but
```text
foo
    ok 1 -
foo
    ok 2 -
foo
    ok 3 -
    1..3
ok 1 - tests
1..1
```
doesn't.
I'll need to check what the parser is emitting.

**Comment by suic86** [comment]
I've created an [issue](https://github.com/codewars/raku-tap2codewars/issues/1) in raku-tap2codewars.

**Comment by kazk** [comment]
Thanks!
