### ISSUE TITLE
Add Dart 2.14

### ISSUE THREAD

**Issue by alexobviously** [codewars/runner#145]
Please complete the following information:

- Name: Dart
- Version: 2.14
- Release Note/Changelog: The current version (2.8) is over a year out of date, and doesn't support null safety, so much of the code we can write with it doesn't really reflect the sort of code we actually write for real projects.

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
Deployed. [87 kata](https://github.com/codewars/content-issues/wiki/List-of-Dart-Kata-to-Update) needs some update.
