### ISSUE TITLE
Upgrade chai to 4.3.4

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/runner#146]
https://github.com/chaijs/chai/releases/tag/v4.3.4

4.3.4 finally fixed `BigInt` display in `should` assertions, which is currently a critical issue with every JS kata that use `BigInt`s in test assertions because this would be displayed when tests with them fail:

```
const chai = require("chai");
const assert = chai.assert;
chai.config.truncateThreshold = 0;

describe("example tests", function() {
  it("returns correct values for example N", function() {
    assert.deepEqual([1n, 2n], [3n, 4n], "Failed when n = 3");
  }); 
});
```

![image](https://user-images.githubusercontent.com/14909989/133362677-a2f25235-360c-48c5-bb87-956db8b88b0f.png)

**Comment by hobovsky** [comment]
There's a known workaround, and it was planned to be documented but I never got to this: https://github.com/codewars/docs/issues/257

But now, since it got fixed in Chai itself, it's even better.

**Comment by kazk** [comment]
Updated in JavaScript Node 12 and TypeScript 4.2.
