### ISSUE TITLE
Add non-native assembly languages?

### ISSUE THREAD

**Issue by nomennescio** [codewars/runner#149]
It might be interesting to add non-test-platform-native assembly languages, by running the tests through an emulator/simulator. Given that I see no fundamental objection other than a limit on execution time, is that something you could consider?

It would be great to add ARM, and even older 8 or 16 bit CPUs are worthy candidates, given that many still have a vibrant community.

**Comment by elimisteve** [comment]
Adding WASM would be cool :-)

**Comment by kazk** [comment]
We can consider based on the following:

- the amount of work required to add support
- performance
- maintenance/operational cost (e.g., image size)
- demand

Please open separate issues to request and discuss.
