### ISSUE TITLE
Add Qiskit

### ISSUE THREAD

**Issue by artnoage** [codewars/runner#150]
Please complete the following information about the language:

- Name: Qiskit
- Website: Qiskit
- Language Version:

The following are optional, but will help us add the language:

- Test Frameworks:
- How to install:
- How to compile/run:
- Any comments: First of all I would like to apologize if this "framework/language" does not apply to your scope. I think that non just qiskit but any language related to quantum computing would be a good addition.

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by artnoage** [comment]
I totally understand your point, and to be honest, I indeed thought of some
of this questions before I write my request. It is just that I couldn't
find any decent material for self study, and I thought that such an
introduction in codewars will motivate more people to construct and solve
katas. I know that various groups use these types of frameworks (quiskit,
Q+..etc) to build useful code already but it is may be far from critical
mass.  In any case I "withdraw" my request. Sorry for wasting your time.

**Comment by kazk** [comment]
Closing for now. If anyone wants this, please provide the information asked by the issue template, and a convincing use case.
