### ISSUE TITLE
Update to testing frameWork for COBOL/A new testing framework for COBOL

### ISSUE THREAD

**Issue by LearningFTW** [codewars/runner#154]
COBOL current framework as pointed out by @monadius : 

> The current test framework is just a preprocessor written in Cobol which merges tests and the user code together and replaces some sentences with regular Cobol code

Is it possible for us to switch to a newer testing framework / preprocessor / or whatever that has most if not all tools that are needed to write Katas in COBOL because as it is, it is impossible to translate a lot of katas even if we have people that are willing to simply because the frame work is missing a lot of things.

**Comment by kazk** [comment]
Yeah, we can switch to something else.
Can you create an example "modern" COBOL project?

**Comment by LearningFTW** [comment]
sure.

**Comment by LearningFTW** [comment]
examples added

**Comment by kazk** [comment]
No, I meant an example of a new COBOL project setup you're proposing.
What are you going to use? How to install it? How should the files be handled?

For example, current setup (under `/workspace/`) looks like:

```text
.
└── src/
    ├── main/
    │   └── cobol/
    │       ├── PRELOADED.cpy
    │       └── solution.cbl
    └── test/
        ├── cobol/
        │   ├── tests.cbl
        │   ├── ZUTZCPC.CBL
        │   ├── ZUTZCPD.CPY
        │   └── ZUTZCWS.CPY
        └── resources/
            └── config
```

Environment set up:
```bash
mkdir -p /workspace/target
cobc -x -std=ibm -O2 -o /workspace/target/ZUTZCPC /workspace/src/test/cobol/ZUTZCPC.CBL

# Used by GNU Cobol to locate copybooks
export COBCPY=/workspace/src/main/cobol:/workspace/src/test/cobol
# Used by GNU Cobol to locate .so files
export COB_LIBRARY_PATH=/workspace/target
# Original program to be tested
export SRCPRG=/workspace/src/main/cobol/solution.cbl
# Copy of original program with test code inserted (created by ZUTZCPC)
export TESTPRG=/workspace/target/generated_tests.cbl
# Unit test cases
export UTESTS=/workspace/src/test/cobol/tests.cbl
# Names of files containing standard test code
export UTSTCFG=/workspace/src/test/resources/config
```

To test:
```bash
# Generate the test code
/workspace/target/ZUTZCPC
# Compile and run the tests
cobc -x -std=ibm-strict -O2 -o /workspace/target/tests /workspace/target/generated_tests.cbl
/workspace/target/tests
```

I think creating a repository is the easiest way to show me.

**Comment by LearningFTW** [comment]
Misread your comment, and yeah ill create a repository, easier for both. 

though it will have to wait a bit (currently on vacation and its ending a in a couple of days so busy right now).

**Comment by monadius** [comment]
A new COBOL test framework is [ready](https://github.com/monadius/cobol-codewars).

@LearningFTW I would like to hear your comments and suggestions.

@kazk Could you run all examples in the Codewars environment and show the output results? 

It would be also nice to upgrade Codewars GnuCOBOL version. My local GnuCOBOL version is 3.1.2.0. I think the GnuCOBOL version should be displayed when the language version is selected (now it is `IBM` but it would be better to have something like `GnuCOBOL 3.1.2 (IBM)`).

**Comment by kazk** [comment]
Cool, I'll try it during the week.

About the version, we'll need to add a new version anyway to introduce this (unless you made it backwards compatible).

I think `GnuCOBOL 3.1.2 (IBM)` is too long to fit. `Gnu 3.1 (IBM)`?

The current version is 2.2 (https://packages.ubuntu.com/focal/gnucobol).

**Comment by kazk** [comment]
> Could you run all examples in the Codewars environment and show the output results?

If you just want to see how the output is rendered, you can use Kumite. Disable the tests, and paste the output:

```python
print("""
<DESCRIBE::>Test Group

<IT::>Passing Test

<PASSED::>Test Passed

<COMPLETEDIN::>5

<IT::>Failing Test

<FAILED::>Test Failed!

<COMPLETEDIN::>5

<COMPLETEDIN::>10
""")
```

![image](https://user-images.githubusercontent.com/639336/140690814-3dfbab28-29b9-4668-9ace-71bce01e4e9f.png)

**Comment by monadius** [comment]
I don't know how much GnuCOBOL changed between versions. So my test framework may be compatible with GnuCOBOL 2.2. But it is better to update it anyway.

`Gnu 3.1 (IBM)` is good. Another option is `3.1.2 (IBM)` (without Gnu).

**Comment by kazk** [comment]
No, I meant the tests. If we change the test framework for the current version, all the existing kata will break unless you made it compatible. Codewars doesn't have a way to specify the test framework used for the language per kata at the moment.

So I'll make the runner to ignore the test framework id for the new `3.1` version and use the new test framework even if the request had `testFramework: "zut"`. Once the old content is updated, I'll update Codewars to send the correct id.

**Comment by kazk** [comment]
@monadius 

It works! Can you transfer the repo to the Codewars org? Not sure if you have enough permission to do that. If not, can you invite me to the project?
I'll open some issues on the repo after transferring to make some changes. Nothing major, though.

**Comment by monadius** [comment]
@kazk I tried to transfer the ownership but I don't have permissions to create repositories at codewars. So I added you as a collaborator. Do I need to give you any special permissions?

**Comment by kazk** [comment]
Thanks for the invite. I accepted it, but can't access the settings page. I think I need the admin role.

**Comment by monadius** [comment]
I don't think it works for personal repositories. It only possible for organizations to assign different roles to collaborators. It would be easier if you create a new empty repository and I will push everything to it (after that I will delete my repository).

**Comment by kazk** [comment]
I remember we did this before, and found https://github.com/codewars/codewars-runner-cli/issues/747#issuecomment-511177424

That worked, so can you transfer to my account?

**Comment by monadius** [comment]
I started the transfer to your account.

**Comment by kazk** [comment]
Thanks! Transferred to https://github.com/codewars/cobol-test and opened some issues.

**Comment by kazk** [comment]
I'll deploy it over the weekend, or early next week.

**Comment by kazk** [comment]
Deployed

**Comment by LearningFTW** [comment]
@kazk : thanks a lot for that ;)
