### ISSUE TITLE
Add C# 10

### ISSUE THREAD

**Issue by stil** [codewars/runner#156]
Please complete the following information:

- Name: C#
- Version: 10
- Release Note/Changelog: https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10

C# 10 has file-scoped namespace declarations which allow for a more concise syntax, especially useful for Katas where solutions are short.

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
I'll update #95 to C# 10 instead. .NET 6 is LTS release too.
