### ISSUE TITLE
Add Java 17

### ISSUE THREAD

**Issue by FArekkusu** [codewars/runner#162]
- Name: Java
- Version: 17
- Release Note/Changelog: [release notes index page](https://www.oracle.com/java/technologies/javase/jdk-relnotes-index.html) (to not include separate links for versions 12-17). The most noticeable features are:
  - `switch` expressions
  - multiline strings (known as "text blocks")
  - data classes (known as "records")
  - `instanceof` pattern matching
  - `switch` pattern matching (**preview feature v1**)
  - QoL improvements in the form of new methods, new built in classes, optimizations etc.

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by Madjosz** [comment]
JDK 16 finally breaks the [reflective access on Java internals](https://openjdk.java.net/jeps/396) if that is of any relevance for Katas or the code runner.

**Comment by kazk** [comment]
Deployed Java 17 and running a script to update the compatible kata. Most of them were compatible when I tested locally.

I'll update https://github.com/codewars/content-issues/wiki/List-of-Java-Kata-to-Update later.

**Comment by kazk** [comment]
33 kata need manual update. https://github.com/codewars/content-issues/wiki/List-of-Java-Kata-to-Update
