### ISSUE TITLE
Prepare for upcoming Factor 0.99 release

### ISSUE THREAD

**Issue by nomennescio** [codewars/runner#166]
In #100 I requested that the Factor 0.98 runner be adapted to be called using a re-generated Factor image, which does compile Factor libraries, and leads to reduced runtimes for ALL Factor CW test code executions. 

I'm not sure how Factor is currently called, as the runners remain invisible to me, but I suspect something akin to what I originally suggested:
`FACTOR_ROOTS="$repo_root:$example_dir" factor -run=kata.tests`

If Factor is called slightly different:
`FACTOR_ROOTS="$repo_root:$example_dir" factor -i=updated-factor-image.image -run=kata.tests`
it will start using such a re-generated image, instead of the default `factor.image`.

As an upcoming Factor 0.99 release is being prepared right now, I'm thinking ahead of a migration path towards this new release. Next to allowing faster run times, generating a new Factor image also allows for Codewars specific configurations/tweaks, which would guard against potential breaking changes in a 0.99 release, as well as the possibility to apply local patches. Therefore introducing the use of a re-generated image has several clear benefits.

My request is to setup an archive similar to codewars/testest (or maybe even that very same archive?), where such a regenerated image specific for Codewars is stored, which is then used subsequently during deployment (I'm not sure how Factor is currently being deployed in the runner, but in the test code of codewars/testest the Linux version of Factor gets explicitly downloaded each time the tests are run). This archive could either contain only that image, or be combined with the original Factor distribution.

Furthermore, the runner would need to add the mentioned flag to use the regenerated image when running Kata testcode.
The regenerated image itself can be created from within Factor, and that can be done with Factor code, hence any proposed customization can just be put under source control as a kind of "patch" in this archive, with a script that when run recreates the regenerated image. In that way you can apply quality assurance on the regenerated image.

**Comment by kazk** [comment]
Tests are executed with `factor -run=$name` where `$name` is extracted from the submitted tests.

> (I'm not sure how Factor is currently being deployed in the runner, but in the test code of codewars/testest the Linux version of Factor gets explicitly downloaded each time the tests are run).

The container image for Factor is built with the following Dockerfile:
```dockerfile
# qualified/factor:0.98
FROM ubuntu:18.04

ENV LANG=C.UTF-8

RUN set -ex; \
    useradd --create-home codewarrior; \
    mkdir -p /workspace; \
    chown -R codewarrior:codewarrior /workspace;

RUN set -ex; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        wget \
        ca-certificates \
    ; \
    rm -rf /var/lib/apt/lists/*;

RUN set -ex; \
    mkdir -p /opt; \
    cd /opt; \
    wget -q -O - https://downloads.factorcode.org/releases/0.98/factor-linux-x86-64-0.98.tar.gz | tar xzf -; \
# To minimize the size, remove misc/ (editor support, icons), some of extra/ (extra libs and apps)
    rm -rf \
        /opt/factor/misc \
        /opt/factor/extra/bunny \
        /opt/factor/extra/images/testing \
        /opt/factor/extra/usa-cities \
        /opt/factor/extra/clutter \
        /opt/factor/extra/gstreamer \
        /opt/factor/extra/websites \
        /opt/factor/extra/benchmark \
        /opt/factor/extra/gpu \
        /opt/factor/extra/snake-game \
        /opt/factor/extra/project-euler \
        /opt/factor/extra/rosetta-code \
        /opt/factor/extra/audio/engine/test \
        /opt/factor/extra/talks \
    ;

# Add testest
RUN set -ex; \
    mkdir -p /opt/factor/work/tools/testest; \
    wget -q -O - https://raw.githubusercontent.com/codewars/testest/v0.2.0/tools/testest/testest.factor > /opt/factor/work/tools/testest/testest.factor;

ENV PATH=/opt/factor:$PATH \
    FACTOR_ROOTS=/workspace

USER codewarrior
WORKDIR /workspace
```

You can use `qualified/factor:0.98` image to run https://github.com/codewars/testest/tree/master/example like the following:

```bash
cd example

WORKSPACE=/workspace/
C=$(docker container create --rm -w $WORKSPACE qualified/factor:0.98 factor -run=kata.tests)
docker container cp ./. $C:$WORKSPACE
docker container start --attach $C
```
This is basically what the runner does.

If you want to experiment, do whatever you want with the Dockerfile, build the image, then run this command.

**Comment by nomennescio** [comment]
OK, I will try to create something using this format, and come up with a proposal. For now I will use a branch in my fork of codewars/testest, and share that with you for your feedback.

**Comment by nomennescio** [comment]
I've come up with a solution which modifies the above example code slightly, and put that into this archive under the `docker` folder in my `factor-reimage` branch. The files point to a not yet commited v0.2.1 release, so if you want to test this, you might need to change that slightly. Can you check if this is suitable to be used on Codewars?

If everything works, as a postprocessing step to reduce Docker image size, `factor.image` can be replace by `factor-codewars.image`. If you so desire, the docker scripts needs to be adapted slightly.

**Comment by kazk** [comment]
I'll try taking a look during this week. Can you post the link to your branch? I don't see it in https://github.com/codewars/testest/branches

**Comment by nomennescio** [comment]
OK, thanks. Does this work for you : https://github.com/nomennescio/testest/tree/feature-reimage

In the meantime I will make some additional changes on the same branch.

**Comment by kazk** [comment]
You can also open a pull request from that branch. That makes it easier to review, ask any questions, and get notified when you push additional changes.

**Comment by nomennescio** [comment]
I've noticed that Docker supports building images from a directory in a github archive. If you're comfortable with that, I could rewrite the current multiple references to an explicit release, with a more general reference to 'master'. I think that would also allow to ditch all the wgets. I assume you would need to manually build a Docker image anyway, so plenty of opportunity to check the resulting image before actually deploying it on CW.

**Comment by nomennescio** [comment]
I'm starting to understand the "issues" with Docker; after overwriting `factor.image` the docker image has nearly doubled in size due to it still keeping the overwritten old file in the image. Only solution seems to be to do everything in a single RUN command, i.e. with shell commands. That is pretty stupid. On paper multi-stage might help, but I didn't succeed yet with that.

**Comment by nomennescio** [comment]
Committed solution with Dockerfile that does not increase docker image. This is already very useful to me, because it allows me to test and run Factor locally in a very similar environment to Codewars, which is very helpful to test locally.

**Comment by nomennescio** [comment]
Closed pull request, as the result is useful on its own. @kazk can you check if this is something you can also readily integrate into CW? The regenerated `factor.image` does lead to a speedup in executing Factor. If needed I can create a new pull request for additional changes.

**Comment by kazk** [comment]
Thanks, I'm going to try it soon. I'll let you know if I have any questions.

I might set up a GitHub Actions to build and push an image whenever a new tag is pushed to that repo. We can have an image `ghcr.io/codewars/factor:0.98-testest-v0.2.0` automatically built, for example. The code runner can use the image.

**Comment by kazk** [comment]
I can't build the image on my laptop with `docker build -t factor:latest https://github.com/codewars/testest.git`.

I get `unknown-cpuinfo-line` error (https://github.com/factor/factor/issues/2315).

```
+ cd /opt
+ wget -q -O - https://downloads.factorcode.org/releases/0.98/factor-linux-x86-64-0.98.tar.gz
+ tar xzf -
+ rm -rf /opt/factor/misc /opt/factor/extra/bunny /opt/factor/extra/images/testing /opt/factor/extra/usa-cities /opt/factor/extra/clutter /opt/factor/extra/gstreamer /opt/factor/extra/websites /opt/factor/extra/benchmark /opt/factor/extra/gpu /opt/factor/extra/snake-game /opt/factor/extra/project-euler /opt/factor/extra/rosetta-code /opt/factor/extra/audio/engine/test /opt/factor/extra/talks
+ bash -
+ cd /opt/factor
+ ./factor -run=codewars.imager
Loading vocab:gmodule/GModule-2.0.gir
resource:basis/bootstrap/image/upload/upload.factor

4: USING: bootstrap.image checksums checksums.openssl cli.git fry
                                                             ^
unknown-cpuinfo-line
string "vmx flags"
```

I'll open a PR to set up a GitHub Action to build the image so I can pull it to test.

**Comment by kazk** [comment]
Image was built correctly: https://github.com/codewars/testest/pkgs/container/factor

A new image will be built automatically whenever you push a new tag.

We can run with the following now:

```bash
IMAGE=ghcr.io/codewars/factor:0.98-testest-v0.2.1-test # versioned
# or IMAGE=ghcr.io/codewars/factor:latest
WORKSPACE=/workspace/
C=$(docker container create --rm -w $WORKSPACE $IMAGE factor -run=kata.tests)
docker container cp ./. $C:$WORKSPACE
docker container start --attach $C
```

There shouldn't be any problem using this, but I'll test it to make sure.

**Comment by kazk** [comment]
I've tested against all published Factor kata, and it was compatible (the author's solution passes the tests) :tada:

**Comment by nomennescio** [comment]
Sorry, I somehow missed your comments! Great news! So that means that if a release is tagged, automatically a new build image is deployed on Codewars? How fancy!

**Comment by nomennescio** [comment]
> I can't build the image on my laptop with `docker build -t factor:latest https://github.com/codewars/testest.git`.
[..]
>```
> unknown-cpuinfo-line
> string "vmx flags"
> ```
> 
> I'll open a PR to set up a GitHub Action to build the image so I can pull it to test.

The unknown-cpuinfo-line does not occur in the Factor 0.98 sources, and neither the string "vmx flags" . It does occur in the latest (pre-0.99) Factor images. It might be that you're running the wrong version of Factor locally?

**Comment by kazk** [comment]
> So that means that if a release is tagged, automatically a new build image is deployed on Codewars?

No, it doesn't deploy to Codewars (the code runner service) automatically. It automatically builds and pushes the image to the GitHub Container Registry for anyone to use.
I still need to rebuild and deploy the code runner service to use it. This is intentional because I wouldn't want the runner to use the latest image available for stability and efficiency.

If you're happy with the new Docker image, we can release v0.2.1, and I can deploy it.

> It might be that you're running the wrong version of Factor locally?

No, the error happened while building with `docker build -t factor:latest https://github.com/codewars/testest.git`, so it happened inside a container using Factor installed there.

I just tried again:
```
Step 8/11 : RUN set -ex;     cd /opt;     wget -q -O - https://downloads.factorcode.org/releases/${FACTOR_VERSION}/factor-linux-x86-64-${FACTOR_VERSION}.tar.gz | tar xzf -;     cd /opt/factor;     rm -rf         ./misc         ./extra/bunny         ./extra/images/testing         ./extra/usa-cities         ./extra/clutter         ./extra/gstreamer         ./extra/websites         ./extra/benchmark         ./extra/gpu         ./extra/snake-game         ./extra/project-euler         ./extra/rosetta-code         ./extra/audio/engine/test         ./extra/talks     ;     ./factor -run=codewars.imager;
 ---> Running in 44b13655ad91
+ cd /opt
+ wget -q -O -+ tar xzf -
 https://downloads.factorcode.org/releases/0.98/factor-linux-x86-64-0.98.tar.gz
+ cd /opt/factor
+ rm -rf ./misc ./extra/bunny ./extra/images/testing ./extra/usa-cities ./extra/clutter ./extra/gstreamer ./extra/websites ./extra/benchmark ./extra/gpu ./extra/snake-game ./extra/project-euler ./extra/rosetta-code ./extra/audio/engine/test ./extra/talks
+ ./factor -run=codewars.imager
Loading vocab:gmodule/GModule-2.0.gir
resource:basis/bootstrap/image/upload/upload.factor

4: USING: bootstrap.image checksums checksums.openssl cli.git fry
                                                             ^
unknown-cpuinfo-line
string "vmx flags"
```
As you can see, it's installing and using 0.98. The bug was fixed in https://github.com/factor/factor/commit/87022ea3b98875d432f1637f5db56b92ac35e058 (2020-06-26) by adding `vmx-flags`. 0.98 was released on 2018-07-31. `vmx-flags` is not defined there https://github.com/factor/factor/blob/0.98/basis/unix/linux/proc/proc.factor#L51

**Comment by nomennescio** [comment]
.> As you can see, it's installing and using 0.98. The bug was fixed in [factor/factor@87022ea](https://github.com/factor/factor/commit/87022ea3b98875d432f1637f5db56b92ac35e058) (2020-06-26) by adding `vmx-flags`. 0.98 was released on 2018-07-31. `vmx-flags` is not defined there https://github.com/factor/factor/blob/0.98/basis/unix/linux/proc/proc.factor#L51

Yet another reason to move to 0.99 when it is released

**Comment by nomennescio** [comment]
> If you're happy with the new Docker image, we can release v0.2.1, and I can deploy it.

I'm about to make a final update with actual lib content for inexact comparisons of numbers (see also https://github.com/codewars/testest/issues/4) in a couple of days.

Maybe it's a good idea to combine that into v0.3.0. When Factor 0.99 is released I expect I need to do some patches and then v0.4.0 could be done.

If you're fine with testing out the new Docker image setup, we can release v0.2.1 as an additional intermediate release. The only changes since v0.2.0 are those Docker changes. A minor version bump would indeed be fitting.

**Comment by kazk** [comment]
> I'm building and running on Debian, and I don't have the issue.

Is the kernel older than v5.6 (`uname -srm`)? It was added in https://github.com/torvalds/linux/commit/14442a159cf488c05bd5639c9fd5665385b9ab39

**Comment by nomennescio** [comment]
> > I'm building and running on Debian, and I don't have the issue.
> 
> Is the kernel older than v5.6 (`uname -srm`)? It was added in [torvalds/linux@14442a1](https://github.com/torvalds/linux/commit/14442a159cf488c05bd5639c9fd5665385b9ab39)
```
$ uname -srm
Linux 5.10.0-11-amd64 x86_64
```

**Comment by nomennescio** [comment]
I just noticed how you integrated the Docker images into https://github.com/codewars/testest, cool!

**Comment by nomennescio** [comment]
I also just noticed you changed the Dockerfile. A bit less happy with that. The changes I made explicitly allowed for patches to be  made to the Factor distribution, which will be necessary in the near future, just before the factor.image is rebuild. Furthermore, the use of ARG enabled me to build and test experimental features before releasing them into the archive using the same Dockerfile directly from my fork by running:
``` docker build --no-cache --progress=plain --build-arg TESTEST_URL=https://raw.githubusercontent.com/nomennescio/testest/feature-margins -t factor:0.98 https://github.com/nomennescio/testest.git#feature-margins
```
That is now broken.

**Comment by kazk** [comment]
> The changes I made explicitly allowed for patches to be made to the Factor distribution, which will be necessary in the near future, just before the factor.image is rebuild. 

I don't think I understand this. Can you elaborate?

> Furthermore, the use of ARG enabled me to build and test experimental features before releasing them into the archive using the same Dockerfile directly from my fork by running:

```bash
docker build --no-cache --progress=plain --build-arg \
TESTEST_URL=https://raw.githubusercontent.com/nomennescio/testest/feature-margins \
-t factor:0.98 https://github.com/nomennescio/testest.git#feature-margins
```
Isn't that equivalent to the following?
```bash
docker build --no-cache --progress=plain \
    -t factor:0.98 https://github.com/nomennescio/testest.git#feature-margins
```
And you should already have that repo locally, and most likely on that branch, so you don't even need to clone or switch branches:
```bash
docker build --no-cache --progress=plain -t factor:0.98 .
```
Or use Factor 0.99
```bash
docker build --no-cache --progress=plain --build-arg FACTOR_VERSION=0.99 -t factor:latest .
```

**Comment by nomennescio** [comment]
> > The changes I made explicitly allowed for patches to be made to the Factor distribution, which will be necessary in the near future, just before the factor.image is rebuild.
> 
> I don't think I understand this. Can you elaborate?

The mechanism allows to overwrite code in basis, core, and extra directories when needed, thereby allowing to patch a release to keep existing Factor katas working without needing to introduce breaking changes between releases. It might also be needed if some of my code is integrated back into the Factor distribution. I'm currently working on making the testest library work with multiple backends besides Codewars. It would allow patching to keep the existing code working using a variant tuned  for Codewars.

And it needs to be done in between the Factor download and the reimage, to avoid nearly doubling the Docker image.

**Comment by kazk** [comment]
> And it needs to be done in between the Factor download and the reimage, to avoid nearly doubling the Docker image.

I don't know the details of patching, and I'm not sure if I want us to be doing that (separate discussion), but isn't that done in `codewars.imager`? It's still done in the same stage like before:

```dockerfile
RUN set -ex; \
    cd /opt; \
    wget -q -O - https://downloads.factorcode.org/releases/${FACTOR_VERSION}/factor-linux-x86-64-${FACTOR_VERSION}.tar.gz | tar xzf -; \
# To minimize the size, remove misc/ (editor support, icons), some of extra/ (extra libs and apps)
    cd /opt/factor; \
# ...
# reimage factor.image
    ./factor -run=codewars.imager;
```

**Comment by nomennescio** [comment]
> > Furthermore, the use of ARG enabled me to build and test experimental features before releasing them into the archive using the same Dockerfile directly from my fork by running:
> 
> ```shell
> docker build --no-cache --progress=plain --build-arg \
> TESTEST_URL=https://raw.githubusercontent.com/nomennescio/testest/feature-margins \
> -t factor:0.98 https://github.com/nomennescio/testest.git#feature-margins
> ```
> 
> Isn't that equivalent to the following (with the new Dockerfile)?
> 
> ```shell
> docker build --no-cache --progress=plain \
>     -t factor:0.98 https://github.com/nomennescio/testest.git#feature-margins
> ```

Yes, except for the use of the deploy.sh to download the Factor files from Github.

> 
> And you should already have that repo locally, and most likely on that branch, so you don't even need to clone or switch branches:
> 
> ```shell
> docker build --no-cache --progress=plain -t factor:0.98 .
> ```
>

Well I develop on multiple platforms, and want to check building Docker in a clean dir.

> Or use Factor 0.99
> 
> ```shell
> docker build --no-cache --progress=plain --build-arg FACTOR_VERSION=0.99 -t factor:latest .
> ```

That is indeed a nice change

**Comment by nomennescio** [comment]
> > And it needs to be done in between the Factor download and the reimage, to avoid nearly doubling the Docker image.
> 
> I don't know the details of patching, and I'm not sure if I want us to be doing that (separate discussion), but isn't that done in `codewars.imager`? It's still done in the same stage like before:
> 
> ```dockerfile
> RUN set -ex; \
>     cd /opt; \
>     wget -q -O - https://downloads.factorcode.org/releases/${FACTOR_VERSION}/factor-linux-x86-64-${FACTOR_VERSION}.tar.gz | tar xzf -; \
>     cd /opt/factor; \
> # ...
> # reimage factor.image
>     ./factor -run=codewars.imager;
> ```

The imager doesn't patch, it only recompiles everything.

**Comment by kazk** [comment]
> Yes, except for the use of the deploy.sh to download the Factor files from Github.

```bash
docker build --no-cache --progress=plain \
    -t factor:0.98 https://github.com/nomennescio/testest.git#feature-margins
```
Does that for you. It uses your repository as build context.

**Comment by nomennescio** [comment]
> > Yes, except for the use of the deploy.sh to download the Factor files from Github.
> 
> ```shell
> docker build --no-cache --progress=plain \
>     -t factor:0.98 https://github.com/nomennescio/testest.git#feature-margins
> ```
> 
> Does that for you. It uses your repository as build context.

True. My remark on deploy.sh was about it being tied to the use of ARG.

**Comment by kazk** [comment]
What's missing then?

The new Dockerfile:

1. Get build context that contains the files (remote repository)
2. Start building
3. Copy files from build context (testest, imager)
4. Install Factor and reimage

The old Dockerfile:

1. Get build context that contains the files (remote repository)
2. Start building
3. Copy deploy.sh from build context
4. Install Factor, use deploy.sh to download files (why? it's already in the build context), then reimage

**Comment by nomennescio** [comment]
> I don't know the details of patching, and I'm not sure if I want us to be doing that (separate discussion), but isn't that done in `codewars.imager`? It's still done in the same stage like before:

The patching I'm talking about is new Factor code that would lead to breaking changes in testest code, requiring incompatible changes to the library, invalidating current Katas. It might not be needed at all, I cannot predict that.

**Comment by kazk** [comment]
Current kata will continue to work because I'm not removing Factor 0.98 with the current testest.
I won't remove older language versions until all published kata are updated to the newer version.

**Comment by nomennescio** [comment]
> What's missing then?
> 4. Install Factor, use deploy.sh to download files (why? it's already in the build context), then reimage

I've looked into that, and the build context is only available for COPY and ADD actions as far as I understand. Mounting volumes is not feasible or desirable either.  To prevent the Docker image doubling in size, imager must be run in the same RUN where Factor is downloaded. Any patching need to happen just before the imager is run. At that point the context is not available to copy files from. Maybe you know a solution?

**Comment by nomennescio** [comment]
> Current kata will continue to work because I'm not removing Factor 0.98 with the current testest. I won't remove older language versions until all published kata are updated to the newer version.

I understand, but I prefer to have 0.99 behave the same as 0.98. In this case that seems to be easy to achieve with maybe some light patching, if it's needed at all.

**Comment by nomennescio** [comment]
I'm also OK with introducing patching into the Docker file the moment it's needed. My proposed solution with a separate script does not require awareness of the Docker file. However, both approaches will work.

**Comment by kazk** [comment]
> I understand, but I prefer to have 0.99 behave the same as 0.98.

Why update then? What about 0.100 in the future?

I wouldn't want Factor 0.99 on Codewars to behave differently from the actual Factor 0.99.

> To prevent the Docker image doubling in size, imager must be run in the same RUN where Factor is downloaded. Any patching need to happen just before the imager is run. At that point the context is not available to copy files from. Maybe you know a solution?

The important part is "downloading Factor" and "patching/reimaging" happening in the same `RUN` stage, so changing files and overwriting the image doesn't copy on write. There's no need to download testest/imager files there.

If we decide to patch, we can add `patch.sh` and execute it in the same `RUN`:

```dockerfile
COPY tools/testest/testest.factor /opt/factor/work/tools/testest/testest.factor
COPY codewars/imager/imager.factor /opt/factor/work/codewars/imager/imager.factor
COPY patch.sh /opt/patch.sh

RUN set -ex; \
    cd /opt; \
# Download Factor
    wget -q -O - https://downloads.factorcode.org/releases/${FACTOR_VERSION}/factor-linux-x86-64-${FACTOR_VERSION}.tar.gz | tar xzf -; \
# Apply patch
    bash patch.sh /opt/factor; \
# Reimage (overwrite)
    cd /opt/factor; \
    ./factor -run=codewars.imager;
```

> My proposed solution with a separate script does not require awareness of the Docker file.

`patch.sh` can accept paths if you want it to be independent.

**Comment by nomennescio** [comment]
> > I understand, but I prefer to have 0.99 behave the same as 0.98.
> 
> Why update then? What about 0.100 in the future?

I should clarify; I want 0.99 Factor behavior, but have the testest library behave the same as for 0.98, to not break the current "interface" to Factor users on CW. Even if the testest library would become part of Factor distribution as a non-CW specific framework with different backends.
 
> I wouldn't want Factor 0.99 on Codewars to behave differently from the actual Factor 0.99.

Fully agree, with one small exception; configuration dependent settings might be different when running on CW versus running on the desktop. And you need to be able to set those when building an image for CW, to have CW-specific "default" behavior.

> The important part is "downloading Factor" and "patching/reimaging" happening in the same `RUN` stage, so changing files and overwriting the image doesn't copy on write. There's no need to download testest/imager files there.

Sure, but that's still not a solution on how to "patch" by just overwriting an existing file by a simple copy action. I do not want to actually resort to diffing and applying diffs to the Factor download.
 
> If we decide to patch, we can add `patch.sh` and execute it in the same `RUN`:
> 
> ```dockerfile
> COPY tools/testest/testest.factor /opt/factor/work/tools/testest/testest.factor
> COPY codewars/imager/imager.factor /opt/factor/work/codewars/imager/imager.factor
> COPY patch.sh /opt/patch.sh

> RUN set -ex; \
>     cd /opt; \
> # Download Factor
>     wget -q -O - https://downloads.factorcode.org/releases/${FACTOR_VERSION}/factor-linux-x86-64-${FACTOR_VERSION}.tar.gz | tar xzf -; \
> # Apply patch
>     bash patch.sh /opt/factor; \
> # Reimage (overwrite)
>     cd /opt/factor; \
>     ./factor -run=codewars.imager;
> ```
> 
> > My proposed solution with a separate script does not require awareness of the Docker file.
> 
> `patch.sh` can accept paths if you want it to be independent.

Your patch.sh is very much like my deploy.sh. And if you have a solution to copy files from the context into the image from within patch.sh, great! I couldn't find a solution for that, therefore resorted to wget.

Now that I think of it, it would be possible to copy all required files into the image anyway with COPY beforehand outside Factory tree, then cp/mv them from within patch.sh in RUN.

Something like
```
COPY tools/testest/testest.factor /opt/tools/testest/testest.factor
COPY codewars/imager/imager.factor /opt/codewars/imager/imager.factor
COPY patch.sh /opt/patch.sh
```

and in patch.sh
```
cp /opt/tools/testest/testest.factor /opt/factor/work/tools/testest/testest.factor
cp /opt/codewars/imager/imager.factor /opt/codewars/factor/work/imager/imager.factor
```

That would work, but ofcourse requires more intimate knowledge of how to properly handle Docker, whereas my deploy.sh does not need such knowledge; you only need to tell which Factor files from the library need to go where in the Factor tree.

But again, we could make it more generic now, or postpone actual required changes into the future. I prefer the more generic approach, but the other one is also fine with me.

**Comment by kazk** [comment]
Are you saying Factor 0.99 will include `tools/testest` and `codewars/imager`? That changes everything. Copying to a temporary location first works in that case.

> That would work, but ofcourse requires more intimate knowledge of how to properly handle Docker, whereas my deploy.sh does not need such knowledge; you only need to tell which Factor files from the library need to go where in the Factor tree.

No, it doesn't need to know about Docker or where the files are. The script can be parameterized (`patch.sh from to`). That's also more natural as a script than using environment variables.

Anyway, I think I'm just lost because I'm missing some context. I did not think `deploy.sh` was for "patching".

---

> Fully agree, with one small exception; configuration dependent settings might be different when running on CW versus running on the desktop. And you need to be able to set those when building an image for CW, to have CW-specific "default" behavior.

That's not patching to me. Just configuring, and totally fine.

**Comment by nomennescio** [comment]
In the future Factor might include tools/testest indeed, but not with codewars defaults. The codewars/imager will never be part of Factor, and continues to be valuable for codewars due to improving runtimes.

Let's go for the COPY approach now. I will keep track if in the future I need to do something special like the intermediate directory I proposed. Some issues I might also be able to solve in the imager. Thanks so far! I will trigger a request for updating the Docker image used by the codewars runner when I've finished the new feature-margins, which solves https://github.com/codewars/testest/issues/4

**Comment by nomennescio** [comment]
@kazk I just created release 1.0.0, which is ready to be published on Codewars. Do we need to discuss anything?

**Comment by kazk** [comment]
I don't think so. I'll test the new image, and let you know if I find anything.

**Comment by kazk** [comment]
Tested against all published kata locally, and passed. I'll let you know when it's deployed.

**Comment by kazk** [comment]
Deployed
