### ISSUE TITLE
Add Lean 4

### ISSUE THREAD

**Issue by crabbo-rave** [codewars/runner#167]
Please complete the following information:

- Name: Lean
- Version: 4
- Release Note/Changelog: [Release Note](https://github.com/leanprover/lean4/releases/tag/v4.0.0-m1)

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
> This release is aimed at experimentation with the new features of Lean 4, eventually leading to a full release of 4.0.0 ready for general use.

We can consider when 4.0.0 is out.

**Comment by crabbo-rave** [comment]
Cool. Perhaps we can reopen when the full release of Lean 4 comes out.

**Comment by Seasawher** [comment]
@kazk lean4.0.0 has been released and mathlib has been completely ported over.

**Comment by a-inoue-code** [comment]
@Seasawher Version 4.0 is not out yet! But almost there...
