### ISSUE TITLE
Add D

### ISSUE THREAD

**Issue by lunemec** [codewars/runner#17]
It would be great to see D supported, it is similar to C/C++ but has tons of awesome features.

https://dlang.org

---

- [x] Installing
- [x] Executing 
- [x] Testing support with [custom runner](https://github.com/codewars/unittested/pull/1) based on [`silly`](https://code.dlang.org/packages/silly). [`fluent-asserts`](https://github.com/gedaiu/fluent-asserts) for helpful assertion error message.
- [x] CodeMirror mode (https://codemirror.net/mode/d/)
- [x] Icon

**Comment by static-binary** [comment]
We need this lang

**Comment by kazk** [comment]
Can you help? We need a [custom reporter](https://gitlab.com/szabobogdan3/trial/-/blob/master/doc/reporters.md#extending) that outputs [messages](https://github.com/codewars/runner/blob/main/docs/messages.md) we require.

I know it's possible, but I just haven't had the time. The most helpful contribution will be creating a repository containing a D project with tests with Trial. And Trial configured to use the custom reporter.

But you can also help by posting required steps and snippets here.

**Comment by static-binary** [comment]
I wish I could help, but I don't know how.

**Comment by static-binary** [comment]
How to you even add the compilers?

**Comment by kazk** [comment]
Just like how you'd install on your computer. That depends on your OS, but shouldn't matter how you install.
The part I need help with is setting up a D project with tests using Trial and a custom reporter. I haven't touched D in a long time, but there should be a standard package manager you can use to add Trial.

**Comment by static-binary** [comment]
I don't know if you use nix, but nix has a package for running [D](https://search.nixos.org/packages?channel=21.05&show=dmd&from=0&size=50&sort=relevance&type=packages&query=dmd)

**Comment by kazk** [comment]
> The D language-request being open for ~6.5 years is a good example of that.
>
> https://github.com/codewars/runner/issues/99#issuecomment-956466009

This sound like nothing has been done for ~6.5 years, so let me clarify. The problem when adding test support for D is that, usually, builtin `unittest` block is used to test, but there's no way to customize the output.

Rust is similar with using builtin `#[test]`, but the test output was structured enough to post-process them into something presentable to add initial support (JSON output was added later, so we switched to that).

D outputs something like this:

```text
core.exception.AssertError@code.d(3): unittest failure
----------------
??:? _d_unittest [0x427f9c]
??:? void code.__unittest_fail(int) [0x427e1e]
??:? void code.__unittestL2_1() [0x427d87]
??:? void code.__modtest() [0x427da0]
??:? int core.runtime.runModuleUnitTests().__foreachbody2(object.ModuleInfo*) [0x42a7bc]
??:? int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*)).__lambda2(immutable(object.ModuleInfo*)) [0x430ee2]
??:? int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))).__foreachbody2(ref rt.sections_elf_shared.DSO) [0x43cc69]
??:? int rt.sections_elf_shared.DSO.opApply(scope int delegate(ref rt.sections_elf_shared.DSO)) [0x42e4a8]
??:? int rt.minfo.moduleinfos_apply(scope int delegate(immutable(object.ModuleInfo*))) [0x43cbf5]
??:? int object.ModuleInfo.opApply(scope int delegate(object.ModuleInfo*)) [0x430eb9]
??:? runModuleUnitTests [0x42a69c]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x4282ea]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x428283]
??:? _d_run_main [0x4281ef]
??:? main [0x427e37]
??:? __libc_start_main [0x9008df44]
```

With `unittest` block, a test framework is not really necessary, so not many exists, and existing ones at the time lacked features we needed. Trial didn't exist back then, and I found it much later, towards the end of 2018. If interested, you can read what was tried back in [2017-2018](https://github.com/codewars/codewars-runner-cli/pull/331#issuecomment-306925252).

**Comment by static-binary** [comment]
How did you customize rust then?

**Comment by kazk** [comment]
We didn't. Like I wrote above, Rust's test output had decent structure, and helpful failure messages, so we could parse the test output and transform it. Later, they added support for JSON output, so we switched to that.

It's difficult to do the same for D, and that's why it was decided not to use the `unittest` block.

**Comment by static-binary** [comment]
@kazk How far do you think you are in adding D?

**Comment by kazk** [comment]
I'll be honest. If you don't have anything constructive, please stop commenting. I'm not working on D support at the moment, and I don't know when I will.

Things to do:

- [ ] Set up D project
- [ ] Add tests using Trial
- [ ] Write a custom reporter
- [ ] Configure Trial to use the custom reporter

If you have no idea how to do these, I don't think you can help.

**Comment by maxhaton** [comment]
Hello, I work for the D Language foundation. There are test frameworks for D and testing behaviour can be overrided. 

Let me take a look and I'll give you directions/code as to how to integrate D if you'd like me too.

**Comment by static-binary** [comment]
> Hello, I work for the D Language foundation. There are test frameworks for D and testing behaviour can be overrided.
> 
> Let me take a look and I'll give you directions/code as to how to integrate D if you'd like me too.

You could ping them at @kazk  for a quicker reply just saying. But it may be too annoying.

**Comment by maxhaton** [comment]
I think they have been pinged enough today

**Comment by kazk** [comment]
Hi @maxhaton. Do you mean `unittest` blocks supports custom output now? We need the tests to output our custom [messages](https://github.com/codewars/runner/blob/main/docs/messages.md) to report the results.

Using a simple example from [Unit Testing in Programming in D](http://ddili.org/ders/d.en/unit_testing.html) linked from [Unit Testing - Dlang Tour](https://tour.dlang.org/tour/en/gems/unittesting)

```d
import std.string;

string ordinal(size_t number) {
    return "";
}

unittest {
    assert(ordinal(1) == "1st");
    assert(ordinal(2) == "2nd");
    assert(ordinal(3) == "3rd");
    assert(ordinal(10) == "10th");
}

void main() {
}
```

```bash
$ dmd deneme.d -w -unittest && ./deneme
deneme.d(17): [unittest] unittest failure
1/1 modules FAILED unittests
```

Is there a way to change the output format?

**Comment by kazk** [comment]
If that's not what you meant, I know that `dub test` can be configured to use test frameworks. When I did some research a few years ago, [trial](https://gitlab.com/szabobogdan3/trial) was the only test framework that supported a custom reporter.

**Comment by maxhaton** [comment]
https://run.dlang.io/is/3Ioa5W no framework required.

If you want better error strings from the assertion you can use fluent-assertions or similar. 

The relatively new `-checkaction=context` basically produces a string of the expression that failed as the assertion message.

**Comment by kazk** [comment]
Thanks! The group is missing its `<COMPLETEDIN::>`, but it's almost there. If that's difficult to support, we can drop `@Group`. The next step will be to extract this into a package and make it easy to import/use.

Is it possible to move tests to a sub scope (I don't know how D modules work)? Tests shouldn't interfere with the solution.
I don't know D, so here's an example in Rust:
```rust
fn add(a: i32, b: i32) -> i32 {
    a + b
}

#[cfg(test)]
mod tests {
  // Can access parent scope
  use super::add;
  use foo::Bar; // Only in this module
  // Shared test helper
  fn test_helper() {
  }

  #[test]
  fn test_add() {}
  #[test]
  fn test_foo() {}
}
```

**Comment by Imperatorn** [comment]
If a package is ok then this could be useful 
https://code.dlang.org/packages/silly

Otherwise it's pretty neat to need no extra dependency at all like maxhaton did imo

**Comment by kazk** [comment]
Yeah, we can use packages.

`silly` looks nice.
If it supports customizing the output, we can use that instead. If not, maybe use maxhaton's, but change the syntax to be compatible with it and make it work similar to `silly` by not requiring extra code to set up.
I'd like to make it easy for users to run tests locally if they want, and if we make it compatible with `silly`, they can use that instead locally to see the normal output.

**Comment by kazk** [comment]
`silly` doesn't support custom output, but it's a single file and easy to understand, so I'll derive our version from it. Users can use `silly` locally.

When it's done, I'll create a repo and ask you guys to review/help.

**Comment by kazk** [comment]
Solution:
```d
module solution;

export int add(int a, int b) {
    import std.stdio : stdout;
    stdout.writefln("a = %d, b = %d", a, b);
    return a;
}
```

Test:
```d
module solution_test;

import solution : add;

version(unittest) import fluent.asserts;

@("failing add with fluent asserts")
unittest {
    add(1, 1).should.equal(2).because("1 + 1 == 2");
}

@("failing add with assert")
unittest {
    assert(add(1, 1) == 2);
}
```

Renders:

![image](https://user-images.githubusercontent.com/639336/140261588-c950ba67-6d3e-4568-bddd-b439f388235b.png)


@maxhaton @Imperatorn What do you think of the setup? Is there anything awkward from D users' perspective? Any feedback on https://github.com/codewars/unittested/pull/1 is appreciated.

**Comment by Imperatorn** [comment]
> Yeah, we can use packages.
> 
> `silly` looks nice. If it supports customizing the output, we can use that instead. If not, maybe use maxhaton's, but change the syntax to be compatible with it and make it work similar to `silly` by not requiring extra code to set up. I'd like to make it easy for users to run tests locally if they want, and if we make it compatible with `silly`, they can use that instead locally to see the normal output.

Just fyi there's also
https://code.dlang.org/packages/unit-threaded

And I know some like the
https://code.dlang.org/packages/dshould

**Comment by kazk** [comment]
`unit-threaded` looks way more complex. We can try if that's better, and if it supports custom output.

`dshould` is an assertion library, right? We can install it, and users can choose between `assert`, `fluent.asserts`, and `dshould`.

**Comment by kazk** [comment]
`dshould` requires `unit-threaded`? Tried adding `dshould` to the example, but got unresolvable dependencies:

```text
Unresolvable dependencies to package unit-threaded:
  dshould 1.4.4 depends on unit-threaded >=0.0.0 (optional)
  dshould 1.4.4 depends on unit-threaded ~>1
  fluent-asserts 0.14.0-alpha.9 depends on unit-threaded >=0.0.0 (optional)
```

**Comment by Imperatorn** [comment]
> `dshould` requires `unit-threaded`? Tried adding `dshould` to the example, but got unresolvable dependencies:
> 
> ```
> Unresolvable dependencies to package unit-threaded:
>   dshould 1.4.4 depends on unit-threaded >=0.0.0 (optional)
>   dshould 1.4.4 depends on unit-threaded ~>1
>   fluent-asserts 0.14.0-alpha.9 depends on unit-threaded >=0.0.0 (optional)
> ```

Yeah, sorry. Didn't have time to explain.

Go with silly ☀️

**Comment by static-binary** [comment]
I am just curious, but how is it going so far?

**Comment by kazk** [comment]
:(

I already told you not to comment unless you have something constructive. Not even a week has passed since my last comment. The issue is open because it's not done yet. I still need to build the image, integrate with the runner, configure Codewars, and deploy it. Remember, I wasn't working on this and wasn't planning to. I was able to make some progress last week thanks to helpful D people. I'll try to find some time after work, and close this whenever it's done. Not promising any dates, but will try to do it soon because it's almost there.

You don't need to check my progress. You're only slowing me down by wasting my time.

**Comment by static-binary** [comment]
Sorry.

**Comment by kazk** [comment]
I'll deploy it over the weekend, or early next week.

**Comment by kazk** [comment]
Deployed. Let me know if you find any issues.
