### ISSUE TITLE
The function is correct but gven value in kate is wrong, i did the same solution like in "Solutions"/ Theme of kata :  Looking for a benefactor

### ISSUE THREAD

**Issue by hithub23** [codewars/runner#171]
**Describe the bug**

**To Reproduce**
Provide code to reproduce the behavior or a link to Kumite.

**Expected behavior**

**Screenshots**

**Browser**
If applicable, please provide your browser information.

- OS: [e.g. macOS]
- Browser [e.g. chrome, firefox, safari]

**Additional context**
``

**Comment by DonaldKellett** [comment]
Feel free to drop by our Discord server for Kata-related help: https://discord.com/invite/mSwJWRvkHA
