### ISSUE TITLE
Add Nim 1.6.6

### ISSUE THREAD

**Issue by locriacyber** [codewars/runner#174]
Please complete the following information:

- Name: Nim
- Version: 1.6.6
- Release Note/Changelog:
  - https://nim-lang.org/blog/2022/05/05/version-166-released.html

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by Patitotective** [comment]
Nim v1.6.6 has already being released which solves lots of bugs, might want to update to 1.6.6 instead of 1.6.4.
https://nim-lang.org/blog/2022/05/05/version-166-released.html

**Comment by kazk** [comment]
Added 1.6.6.
96 kata need some updates to enable it. See https://github.com/codewars/content-issues/wiki/List-of-Nim-Kata-to-Update
