### ISSUE TITLE
Add Go 1.18

### ISSUE THREAD

**Issue by illiafox** [codewars/runner#176]
- Name: **Golang**
- Website: [go.dev](https://go.dev/)
- Language Version: `1.18`

A week ago golang devs released [go 1.18](https://github.com/golang/go/milestone/201)

Although, codewars still uses [go 1.12](https://go.dev/doc/go1.12), which was delevoped 3 years ago!
![Screenshot from 2022-03-15 20-00-04](https://user-images.githubusercontent.com/61962654/158442291-2f484486-fbed-4bf1-a5e8-eda1fc33de8c.png)

Release notes: 
[1.13](https://go.dev/doc/go1.13#introduction)
[1.14](https://go.dev/doc/go1.14#introduction)
[1.15](https://go.dev/doc/go1.15#introduction)
[1.16](https://go.dev/doc/go1.16#introduction)
[1.17](https://go.dev/doc/go1.17#introduction)
[1.18](https://go.dev/doc/go1.18#introduction)

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
Deployed

**Comment by kazk** [comment]
7 kata needs some update. https://github.com/codewars/content-issues/wiki/List-of-Go-Kata-to-Update

**Comment by bshore** [comment]
I took care of one of these - [If you can read this...](https://www.codewars.com/kumite/58b0b0b712044dae6d00004f?sel=628314060f20ad39ee419615) - and I can work on some of the others, I just need to solve them first 😃

**Comment by kazk** [comment]
Thanks! I think you forked the approved translation. Can you fork the kata instead? If you don't know what that means, I just added a section about it on https://github.com/codewars/content-issues/wiki/List-of-Go-Kata-to-Update

**Comment by bshore** [comment]
Done! [new fork](https://www.codewars.com/kumite/62831a04d918b30042bff230?sel=62831a04d918b30042bff230)

**Comment by kazk** [comment]
Thanks
