### ISSUE TITLE
Lua rest args do not work properly

### ISSUE THREAD

**Issue by kemptosa** [codewars/runner#177]
**Describe the bug**
The `arg` feature for getting rest arguments from the input of a function is being overridden by what seems to be a separate table containing command line arguments for the interpreter.

**To Reproduce**
```lua
print((function(...)return arg[1] end)(2,3,5))
```
returns `--output=/opt/runner/codewars.lua`

**Expected behavior**
The above code should return the first argument, which is 2.

**Comment by kazk** [comment]
We run Lua tests with `busted --output=/opt/runner/codewars.lua`, which, I believe, is the standard usage. See [busted](https://github.com/Olivine-Labs/busted).

I'll take a look.

**Comment by monadius** [comment]
Lua 5.3 does not use the `arg` variable. Extra arguments are accessed with the `...` expression (see the [reference](https://www.lua.org/manual/5.3/manual.html#3.4.11)).

**Comment by kazk** [comment]
Oh, thanks! I guess `arg` is global and only used for CLI args in 5.3?

@kemptosa the following should work.
```lua
print((function(...)return ({...})[1] end)(2,3,5))
```

**Comment by monadius** [comment]
Yes, `arg` is global table which contains command line arguments ([reference](http://www.lua.org/manual/5.3/manual.html#7)).

**Comment by fcr--** [comment]
You can also obtain the n-th argument from `...` with `select(n, ...)` (and the number of varargs with `select('#', ...)`).
