### ISSUE TITLE
Add Typescript 4.9

### ISSUE THREAD

**Issue by skeate** [codewars/runner#188]
Please complete the following information:

- Name: Typescript
- Version: 4.9
- Release Note/Changelog:
  - https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/
  - https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
We have some kata stuck in TypeScript 2.x...

We currently have TypeScript 2.4, 3.3, 3.8, and 4.2. I'm not adding a new version until those are updated.

See https://github.com/codewars/content-issues/wiki/List-of-TypeScript-Kata-to-Update for how to help.

**Comment by kazk** [comment]
Deployed
