### ISSUE TITLE
Add Coq 8.15 with packages from Coq Platform package set 2022.04.1

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/runner#189]
**We're not going to use Coq Platform, but will use the package set when choosing package versions, so users can use Coq Platform locally.**

---

Please complete the following information:

- Name: Coq Platform
- Version: 2022.04.0
- Release Note/Changelog: https://github.com/coq/platform/releases/tag/2022.04.0

It's been a while since we last updated Coq on Codewars. [Coq 8.12 was released almost 2 years ago back in July 2020](https://github.com/coq/coq/tree/V8.12.0) and back then, Coq Platform wasn't a thing so we just installed the base compiler + a few select packages.

But now Coq Platform is a thing and bundles the base compiler along with a suite of commonly-used open-source libraries (and optionally, some proprietary ones as well), greatly improving the potential of Coq Kata authored on Codewars. The latest Coq Plaform release, [2022.04.0](https://github.com/coq/platform/releases/tag/2022.04.0) at the time of writing, includes Coq 8.15.1 plus a suite of libraries which can all be conveniently installed through a single script.

P.S. can we have codewars/coq (or codewars/coq-platform) Docker image like we have codewars/lean and codewars/agda ?

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by DonaldKellett** [comment]
I've created a repo [DonaldKellett/coq-platform](https://github.com/DonaldKellett/coq-platform) to experiment with and can be transferred to Codewars when/if deemed ready.

**Comment by kazk** [comment]
Created https://github.com/codewars/coq

I wouldn't mind switching the base image to Ubuntu as long as the final image is not huge.

**Comment by kazk** [comment]
Deployed. 12 kata needs to be updated to enable 8.15. https://github.com/codewars/content-issues/wiki/List-of-Coq-Kata-to-Update

You can open requests for additional packages from the package set.
