### ISSUE TITLE
Add Dart 2.14 to Qualified

### ISSUE THREAD

**Issue by dustincatap** [codewars/runner#191]
Please complete the following information:

- Name: Dart
- Version: 2.14

I am not able to select 2.14.

![image](https://user-images.githubusercontent.com/56006524/178084326-1a878abf-f609-41fa-9ee1-5107c265c165.png)

2.14 can be used in codewars (#145), but not in qualified. It would be great to have this support since 2.8 does not support null safety.

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
Enabled 2.14
