### ISSUE TITLE
Runtimes for Nim code are absurdly long

### ISSUE THREAD

**Issue by shirleyquirk** [codewars/runner#194]
**Describe the bug**
The runtime for Nim code cannot be accurate.  Take for example 'Cat years, Dog years', one of the simplest possible kata.
When running a solution the tests report:
`Completed in 0.0031ms` for the standard tests and
`Completed in 0.0186ms` for the random tests

meanwhile the total reported time is 4162ms !!

This obviously has very real effects on more complicated tests, making some of them impossible to run under 12s

**To Reproduce**

Run 'Cat years, Dog years' with any of the solutions, e.g.
```python
proc toYears*(humanYears: int): tuple[humanYears, catYears, dogYears: int] =
  result = (
    humanYears,
    15+int(humanYears>1)*9+int(humanYears>2)*(humanYears-2)*4,
    15+int(humanYears>1)*9+int(humanYears>2)*(humanYears-2)*5
  )
```

**Expected behavior**
Total time should be less than 1ms.

**Screenshots**
![image](https://user-images.githubusercontent.com/31934565/180196298-1f0b55ea-cc58-49a5-94df-8abf46bb872a.png)

**Browser**
If applicable, please provide your browser information.

- OS: Windows 10
- Browser: Edge
- Version: Version 103.0.1264.49 (Official build) (64-bit)

**Additional context**

I can see that code is being compiled with `-d:release`, so that's not the issue, at least.  

The runtime seems proportional to the number of tests written in code, but **not** the number of tests run

e.g.
```python
for i in 0..200:
  test "random test " & $i:
    for j in 0..100:
      let h = rand(25) + 1
      check toYears(h) == sol(h)
````
gives a runtime of 6698ms for 200 tests run
![image](https://user-images.githubusercontent.com/31934565/180203213-2af417dc-4d10-43d1-93dd-04b0ec67cf76.png)

while this (which basically copy pastes the test 17 times)

```python
import macros
macro multiples(x:untyped):untyped =
  result = nnkStmtList.newNimNode()
  for i in 0..16:
    result.add x

multiples:
  test "Random Test":
    for i in 0..100:
      let h = rand(25) + 1
      check toYears(h) == sol(h)
```

sometimes times out, or gives a runtime of just under 12s
![image](https://user-images.githubusercontent.com/31934565/180204260-e66b02aa-1a0e-4e3c-b478-4bb774e89fe8.png)

**Comment by hobovsky** [comment]
It's normal for some languages, for example Scala:

![image](https://user-images.githubusercontent.com/23709795/180212276-4aea696a-0ff6-4aa2-98a0-672ba30ad94c.png)

JVM-based languages like Scala, Kotlin, Clojure(?), seem to have 6-7s of additional startup overhead.

Total time reported includes time for spinning up a container, compilation of source code, starting test framework and discovery of test suites and test cases. Depending on how tests are written, additional discrepancies can  come from time spent on generation of random inputs and running reference solution.

Generally, though, it should not be as much of an issue as it might seem for you. It could make it harder to create performance kata which require stricter control of execution times, and where 3s fluctuations from test run to test run can have significant impact. But for most of kata, it's enough to get ~100 tests run below time limit imposed by the runner, no matter if it takes 1 second for JS, 3 seconds for C++, or 9 seconds for Scala. Nim's container timeout seems to be set to 12 seconds (see [here](https://docs.codewars.com/languages/nim)), so maybe it would be enough to ask and have it increased to 16 seconds?

**Comment by shirleyquirk** [comment]
Thank you for your quick reply,

I understand from the perspective of hosting the code that you have to limit the total time running a kata takes, including compilation time.  

I don't understand why
```python
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
test "foo": check true
```
times out.

perhaps i can try something other than `unittest` to cut down on compile times, and increasing the container timeout sounds like a great idea as well.  where would i be able to make that request, do you know?

**Comment by hobovsky** [comment]
This repository and this thread is a good place, your issue can stay here and probably will be processed by admins soon.

**Comment by error256** [comment]
So there seem to be 2 things: a constant latency and slow compilation of testing code. Both seem to be consistent between Codewars and https://nim.godbolt.org/, so I'm assuming the reasons probably are the same.
An empty file without tests takes 4-4.7 seconds on CW. What is this time, recompiling parts of the standard library? In Compiler Explorer, I see
```
CC: stdlib_digitsutils.nim
CC: stdlib_assertions.nim
CC: stdlib_dollars.nim
CC: stdlib_system.nim
CC: example.nim
```
for an empty file. I don't know, is it possible to save precompiled modules?
5 times `test "foo": check true` is 2698 lines, while 10 times that is [4879 lines](https://nim.godbolt.org/z/hjzo5TYd8). It looks like templated `test` and `check` are inlined everywhere?
Tests without many copies of `test` seem to work OK (just an example; the reference solution usually shouldn't be called for fixed tests):
```nim
import random, strformat

iterator testCases(): int {.closure.} =
  for each in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]:
    yield each
  randomize()
  for i in 1..100:
    yield rand(1000)

proc mul123RefImpl(x: int): int = x * 123

for x in testCases():
  test &"mul123({x})":
    let actual = mul123(x)
    let expected = mul123RefImpl(x)
    check(actual == expected)
```

**Comment by kazk** [comment]
We can increase the timeout if there's nothing we can do. But let's try to figure out what's causing this first, and find any fix/workaround.

> I don't know, is it possible to save precompiled modules?

It should be, or it was possible before at least. We've been testing once while building the container image to generate `nimcache` in `~/.cache/nim/` to avoid recompiling standard libraries on each submission. I just noticed `--trmacros:off` flag used in the actual submissions (added [to prevent easy cheating](https://github.com/codewars/codewars-runner-cli/pull/835)) is missing there, so maybe that's why? It was also missing for Nim 1.0 image, though.

Is there a better way to precompile everything up front? The example test used is minimal, so perhaps only parts of the standard library is precompiled.

**Comment by kazk** [comment]
Compiler flags used:
```bash
nim compile \
  --run \
  --define:release \
  --warnings:on \
  --hints:off \
  --verbosity:0 \
  --stackTrace:on \
  --lineTrace:on \
  --checks:on \
  --trmacros:off \
  tests.nim
```

**Comment by kazk** [comment]
> An empty file without tests takes 4-4.7 seconds on CW. What is this time, recompiling parts of the standard library?

During the image build, a minimal example is compiled to generate some `nimcache` for parts of standard library and test reporter.

<details>
<summary><code>solution.nim</code></summary>

```nim
proc add*(x, y: int): int = x + y
```

</details>
<details>
<summary><code>solution_test.nim</code></summary>

```nim
suite "add":
  test "1 + 1 = 2":
    check(add(1, 1) == 2)
```

</details>
<details>
<summary><code>tests.nim</code></summary>

```nim
import unittest, codewars_output
addOutputFormatter(OutputFormatter(newCodewarsOutputFormatter()))
import solution except test, suite, check # Disallow solution from overriding unittest's identifiers
include solution_tests
```

</details>

The verbose output shows:
```text
CC: stdlib_digitsutils.nim
CC: stdlib_assertions.nim
CC: stdlib_dollars.nim
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: stdlib_exitprocs.nim
CC: stdlib_parseutils.nim
CC: stdlib_math.nim
CC: stdlib_algorithm.nim
CC: stdlib_unicode.nim
CC: stdlib_strutils.nim
CC: stdlib_streams.nim
CC: stdlib_options.nim
CC: stdlib_times.nim
CC: stdlib_hashes.nim
CC: stdlib_sets.nim
CC: stdlib_os.nim
CC: stdlib_strformat.nim
CC: stdlib_terminal.nim
CC: stdlib_unittest.nim
CC: stdlib_pcre.nim
CC: stdlib_tables.nim
CC: stdlib_util.nim
CC: stdlib_nre.nim
CC: ../home/codewarrior/.nimble/pkgs/codewars_output-0.1.0/codewars_output.nim
CC: solution.nim
CC: tests.nim
```

Testing with empty solution and tests with Nim 1.6 shows:

```text
CC: stdlib_digitsutils.nim
CC: stdlib_assertions.nim
CC: stdlib_dollars.nim
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: stdlib_exitprocs.nim
CC: stdlib_parseutils.nim
CC: stdlib_math.nim
CC: stdlib_algorithm.nim
CC: stdlib_strutils.nim
CC: stdlib_streams.nim
CC: stdlib_options.nim
CC: stdlib_os.nim
CC: stdlib_terminal.nim
CC: stdlib_unittest.nim
CC: tests.nim
```

With Nim 1.0:

```text
CC: stdlib_assertions.nim
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: stdlib_strutils.nim
CC: stdlib_sets.nim
CC: stdlib_os.nim
CC: stdlib_terminal.nim
CC: stdlib_unittest.nim
CC: tests.nim
```

**Comment by kazk** [comment]
> a constant latency

Nim 1.6 seems slightly slower than 1.0. ~4-5s vs ~6s for empty tests.

Nim 1.6 is recompiling more modules from the standard library for some reason, but the difference is not that significant.

> slow compilation of testing code

Nim 1.6 can take more than twice as long to compile when the number of `test` in tests is high. Workaround is to avoid having too many `test` like @error256 wrote above.

**Comment by shirleyquirk** [comment]
timing nim's code generation separately from the c compiler pass for a trivial test (`test "foo": check true` 50 times) shows that most of the time is spent during c compilation.

passing `--cc:clang` (using clang instead of gcc) reduces that time dramatically. (for me: gcc takes 13 seconds and clang 7 on a test file consisting only of 50x `test "foo": check true)

reducing the number of tests might be challenging for e.g. [Esolang #3 Custom Paintfuck Interpreter](https://www.codewars.com/kata/5868a68ba44cfc763e00008d) which has 31 tests

refactoring the tests to minimize the number of `test` instantiations does help, by doing this i was able to get that kata to compile in 5s with nim1.0 and 9s with 1.6.  it's a pain, though. maybe with some work it could be automated by writing new `test` or `suite` templates idk.

could you please add `--cc:clang` to the compiler flags and see if that helps?

**Comment by kazk** [comment]
For 50 `test "foo": check true`, `--cc:clang` does help. ~11s vs ~7s on my laptop.

I still think the number of `test` should be reduced anyway, but we can start using `--cc:clang`.

**Comment by kazk** [comment]
Switched to Clang

**Comment by shirleyquirk** [comment]
Thank you! Esolang #3 now works without any refactoring.  Yes, number of tests should be reduced as well, but for now this is a great improvement.
