### ISSUE TITLE
node-canvas is missing in Node 10+ environments

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/runner#196]
I believe this discussion has happened roughly a million years ago, but apparently the previous discussions can't be found anymore.

[node-canvas](https://github.com/Automattic/node-canvas) is currently only available in Node v8. There are a few katas that uses canvas (such as `Canvas Fun #1` to `Canvas Fun #5`), and they will be stuck at Node v8 until the package is installed in newest Node versions.

Were there some difficulties in installing the package in Node v10+ environments?

**Comment by kazk** [comment]
Added to Node 14

**Comment by kazk** [comment]
The API changed, so the kata needs to be fixed by

```diff
- const Canvas = require('canvas');
- const Image = Canvas.Image
+ const {createCanvas: Canvas, Image} = require('canvas');
```

The tests can be updated by adding `const Test = require('@codewars/test-compat');` or rewriting assertions with `chai`.
