### ISSUE TITLE
Carbon

### ISSUE THREAD

**Issue by photon-e** [codewars/runner#198]
Please complete the following information about the language:

- Name: Carbon
- Website: https://github.com/carbon-language/carbon-lang
- Language Version: 0.1

The following are optional, but will help us add the language:

- Test Frameworks:
- How to install:
- How to compile/run:
- Any comments: (e.g., what's interesting about this language)

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
Closing because of the project status:

> #### Project status
> Carbon Language is currently an experimental project. There is no working compiler or toolchain.

A new request can be opened when it's ready to be used.
