### ISSUE TITLE
Add Lean v3.20.0

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/runner#2]
Please complete the following information:

- Name: Lean
- Version: 3.20.0
- Release Note/Changelog: https://github.com/leanprover-community/lean/blob/master/doc/changes.md#3200c-9-september-2020

---

:+1: reaction _might_ help.

**Comment by kazk** [comment]
Deployed. We have 21 kata to update https://github.com/codewars/codewars.com/wiki/List-of-Lean-Kata-to-Update
