### ISSUE TITLE
Allow TypeScript decorators

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/runner#200]
The use of decorators in TS (4.2) is currently failing at compilation time, because the `tsconfig.json` file is missing `compilerOptions.experimentalDecorators: true`.

Is it possible to activate it in CW's context? Decorators are one of the coolest thing added in recent TS versions (yeah, ok... that's the python guy in me talking... x) ).

**Comment by kazk** [comment]
Added to TypeScript 4.2, but didn't test. Let me know if it doesn't work.

**Comment by Blind4Basics** [comment]
I still get the warning:

> solution.ts:24:10 - error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

**Comment by kazk** [comment]
You're using TypeScript 4.2, right? `tsconfig.json` is:
```json
{
  "compilerOptions": {
    "target": "es2020",
    "module": "commonjs",
    "strict": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "experimentalDecorators": true
  },
  "exclude": ["node_modules"]
}
```

**Comment by Blind4Basics** [comment]
afaik, yes, But the kata I'm trying suffers from the ui bug about ts versions, so I cannot confirm, I fear:

[Functional SQL](https://www.codewars.com/kata/545434090294935e7d0010ab)

* 4.2 not selectable
* clicking on 3.8 makes 4.2 show up
* clicking again on 3.8 makes 3.8 stay

So I don't actually know what version I'm using... 
---
It looks like I'm using 3.x and not 4.2: whne clicking on 3.3, despite 4.2 showing up in the UI, I get error messages about flatMap. I don't get them anymore when clicking on 3.8. So I guess 4.2 doesn't exist (or isn't reachable) for that kata... It is not in the list of TS kata to update, tho.

**Comment by kazk** [comment]
> It is not in the list of TS kata to update, tho.

I think that list is any TypeScript kata stuck in 2.x.

**Comment by kazk** [comment]
Functional SQL seems to have TypeScript 3.3.
There are 335 kata without 4.2 enabled. I'll try running the script to enable it.

**Comment by kazk** [comment]
> But the kata I'm trying suffers from the ui bug about ts version

I haven't figured out why this is happening. I might just remove incompatible versions from the dropdown instead.

**Comment by kazk** [comment]
Closing because decorators work with TypeScript 4.2.

I'll update the list when the background jobs finish.

**Comment by kazk** [comment]
Functional SQL should have 4.2 now.

**Comment by kazk** [comment]
Updated the list. 8 kata left to update.
