### ISSUE TITLE
Update to the latest Ruby 3.0

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/runner#202]
We found a runtime bug in Ruby 3.0 runtime that affects [this beta kata](https://www.codewars.com/kata/62ffcb8cfab8d209ca599d2b/discuss):

```ruby
irb(main):001:0> (1..10).lazy.take(0).map { |x| x - 1 }.to_a
=> [0]

irb(main):002:0> (1..10).take(0).map { |x| x - 1 }.to_a
=> []

RUBY_VERSION
=> "3.0.0"
```

I tested on Ruby 3.1 [here](https://try.ruby-lang.org/) and cannot reproduce this. Maybe 3.0 can be replaced by 3.1?

**Comment by kazk** [comment]
Yeah, I'll update to the latest 3.0.

**Comment by kazk** [comment]
Updated to 3.0.4
