### ISSUE TITLE
Add Haskell 9.2.5

### ISSUE THREAD

**Issue by andys8** [codewars/runner#206]
Please complete the following information:

- Name: Haskell (GHC)
- Version: 9.2.4
- Release Note/Changelog: https://www.haskell.org/ghc/blog/20220728-ghc-9.2.4-released.html

Currently GHC is at 8.8.4 (2 years old) but 9.x and especially 9.2.4 brought interesting changes. 

Stackage has 9.2.4 in its nightly, and it will soon be LTS. I would recommend skipping 9.0 (which currently is LTS).

<https://www.stackage.org/nightly-2022-09-06>

Is there any way to contribute and update / test the image with the new compiler version? It looks like it's not open sourced or I didn't find the image sources.

---

- [x] Open source the image (https://github.com/codewars/haskell)
- [x] Update to GHC 9.2.5 (https://github.com/codewars/haskell/pull/1)
  - [x] Use LTS 20.10 (GHC 9.2.5) 
- [x] Update the reporter to use `itemDuration` (https://github.com/codewars/hspec-formatters-codewars/issues/2)
- [x] Update the image to use the new reporter

**Comment by kazk** [comment]
If I remember correctly, Hspec added some functions that allow us to add durations for each test case/group. https://github.com/codewars/hspec-formatters-codewars should be updated if possible.

**Comment by andys8** [comment]
Opened a pull request with some open questions. Please move discussion there.

https://github.com/codewars/hspec-formatters-codewars/pull/1


> If I remember correctly, Hspec added some functions that allow us to add durations for each test case/group.

I didn't change the implementation to `Formatters.V2`. But the new implementation does seem to have `itemDuration`. In this PR I'd prefer to only update Haskell/GHC and leave functionality as is.

https://hackage.haskell.org/package/hspec-core-2.10.4/docs/Test-Hspec-Core-Formatters-V2.html#g:2

**Comment by andys8** [comment]
Is anything missing here for the update to ghc 9.2 (ignoring item duration reporting)?

**Comment by kazk** [comment]
I added task list to this issue. https://github.com/codewars/runner/issues/206#issue-1363097926
Waiting for LTS, and I also want duration.

**Comment by kazk** [comment]
Deployed.  Thanks @andys8 and @hobovsky.

81 kata to update. https://github.com/codewars/content-issues/wiki/List-of-Haskell-Kata-to-Update

**Comment by JohanWiltink** [comment]
9 kata to update. list updated. all remaining kata have issues opened on them.
