### ISSUE TITLE
Add Node v18

### ISSUE THREAD

**Issue by Chrono79** [codewars/runner#209]
Please complete the following information:

- Name: Javascript
- Version: Node v16
- Release Note/Changelog: [https://nodejs.org/en/blog/release/v16.17.0/](https://nodejs.org/en/blog/release/v16.17.0/)

---

:+1: reaction _might_ help to get this request prioritized.

I don't know why, but a lot of people seems to only know replaceAll and forget replace exists.

**Comment by kazk** [comment]
Can you guys help to update kata stuck in Node 8? https://github.com/codewars/content-issues/wiki/List-of-JavaScript-Kata-to-Update

Updating from Node 10 and up should be much easier.

**Comment by kazk** [comment]
Updated most kata that had Node 10 to 14 by prepending `const Test = require('@codewars/test-compat');` to tests.

42 kata are stuck in Node 10.x. I've only checked a few, but it's mostly doing some crazy stuff for "anti-cheat".

https://github.com/codewars/content-issues/wiki/List-of-JavaScript-Kata-to-Update#list-of-node-10x-kata

If we update these, we can remove Node 10 and 12.

**Comment by Chrono79** [comment]
Ok, I'll try to help with those that I already solved.

**Comment by kazk** [comment]
I'll add Node v18 since we need it for Qualified. I wanted to experiment with ways to avoid concatenation without breaking everything (e.g., use modules if the test contains `import ... "./solution";`), but it will work just like Node v14 because I don't have the time.

Any help to get rid of Node 10.x is still appreciated.

**Comment by kazk** [comment]
Deployed. I'll try to update Node 14 kata automatically later.
