### ISSUE TITLE
Add Kotlin 1.6

### ISSUE THREAD

**Issue by t-animal** [codewars/runner#210]
Please complete the following information:

- Name: Kotlin
- Version: 1.6
- Release Note/Changelog: https://kotlinlang.org/docs/whatsnew16.html

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
All Kotlin kata must be updated to 1.5 before considering 1.6. See https://github.com/codewars/content-issues/wiki/List-of-Kotlin-Kata-to-Update

**Comment by kazk** [comment]
Kotlin 1.9 was added as requested by a Qualified's customer. I'll run the script to update compatible kata later.

**Comment by kazk** [comment]
11 kata must be updated to enable Kotlin 1.9. See https://github.com/codewars/content-issues/wiki/List-of-Kotlin-Kata-to-Update
