### ISSUE TITLE
Add PCRE

### ISSUE THREAD

**Issue by vk2o** [codewars/runner#213]
Please complete the following information about the language:

- Name: PCRE
- Website:
- Language Version:

The following are optional, but will help us add the language:

- Test Frameworks:
- How to install:
- How to compile/run:
- Any comments: (e.g., what's interesting about this language)

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by Blind4Basics** [comment]
Hello,

The idea of the template is to _actually fill_ it with data. You can reopen the thread/issue if you fill the info properly, otherwise, there isn't much to be done here.

Cheers
