### ISSUE TITLE
Add typescript 4.8,javascript node 17

### ISSUE THREAD

**Issue by muhammedAlySawalhy** [codewars/runner#216]
Please complete the following information:

- Name:typescript and javascript
- Version:4.8 for typescript node 17 for javacript
- Release Note/Changelog:
      javascirpt  new versions support many new features to help working with arrays like groupBy method and groupBymap method also set of new features,typescript 4.8 supports many new typing features to ease the way of typing like method typeof
---

:+1: reaction _might_ help to get this request prioritized.

**Comment by hobovsky** [comment]
There's already #188 for TS 4.7 with an explanation what has to be done before update. Feel free to help.  
There's already #209  for Node 16 with an explanation what has to be done before update. Feel free to help.

Closing as a duplicate.

**Comment by muhammedAlySawalhy** [comment]
Just tell me which kata needs to be updated and I am more happy to update it to best practice in typescript currently cannot find the list o them

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
