### ISSUE TITLE
Add priority_queue crate for rust

### ISSUE THREAD

**Issue by hvox** [codewars/runner#219]
Package name: PriorityQueue.
Language name: rust.
Website: https://crates.io/crates/priority-queue

This crate is very useful to rust developers because many katas can be solved by priority queue in other languages, but rust does not have priority queue in it's standard library, so we need to use external crate for this purpose.

**Comment by error256** [comment]
> rust does not have priority queue in it's standard library

[`std::collections::BinaryHeap`](https://doc.rust-lang.org/stable/std/collections/struct.BinaryHeap.html)?

**Comment by hvox** [comment]
> [`std::collections::BinaryHeap`](https://doc.rust-lang.org/stable/std/collections/struct.BinaryHeap.html)?

I didn't know about this thing. Thanks
