### ISSUE TITLE
Add MIPS

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/runner#22]
Please complete the following information about the language:

- Name: [MIPS](https://en.wikipedia.org/wiki/MIPS_architecture) assembly
- Language Version: [spim](http://spimsimulator.sourceforge.net) (the terminal interface)? But 1) it's a simulator so it might be slow and 2) we probably have to roll our own testing framework. Alternatively, we could look into [cross-compilation](https://stackoverflow.com/a/12482704) or similar to see if we can save effort on the testing framework by using [Criterion](https://github.com/Snaipe/Criterion).

The following are optional, but will help us add the language:

- Test Frameworks: Probably [MIPSUnit](https://www.researchgate.net/publication/314296181_MIPSUnit_A_Unit_Testing_Framework_for_MIPS_Assembly) (is it even open-source?) if we're using `spim`, or make [Criterion](https://github.com/Snaipe/Criterion) work with MIPS (like what we do for NASM)
- How to install: `sudo apt-get install spim` (?) ([source](https://askubuntu.com/a/367173))
- How to compile/run: `spim -file Solution.s` (where `Solution.s` is the solver's MIPS solution file) (?) - refer to the [Ubuntu manpages](http://manpages.ubuntu.com/manpages/cosmic/man1/spim.1.html) for more details
- Any comments: MIPS is a common choice of assembly language in introductory computer architecture courses due to its relatively simple instruction set.

---

:+1: reaction _might_ help.

**Comment by DonaldKellett** [comment]
Closing due to lack of progress. Trying to port a JUnit 4 based testing framework to JUnit 5 without prior experience in either proved to be less straightforward than I initially anticipated, and it seems no one else is interested in picking up and continuing the work here.

**Comment by JW529** [comment]
@kurmasz  Can I have the Java source for MUnit? My gitHub account name is @JW529

**Comment by kurmasz** [comment]
Yes. I can get you set up later this week.

Sent from my iPhone

On Sep 1, 2024, at 11:20 PM, JW529 ***@***.***> wrote:

﻿

@kurmasz<https://github.com/kurmasz> Can I have the Java source for MUnit? My gitHub account name is @JW529<https://github.com/JW529>

**Comment by JW529** [comment]
thanks

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kurmasz** [comment]
This project is actually hosted at bitbucket. Do you have an account there?

**Comment by JW529** [comment]
Oh,I dont have that account. Can I get it via gmail?

**Comment by kurmasz** [comment]
Do you mean e-mail you a .tar file? Or use your gmail address to send a BitBucket invite?

**Comment by JW529** [comment]
Yeah. Can you email me the .tar file?

**Comment by kurmasz** [comment]
I have a better idea: I just made the repo public:  https://bitbucket.org/kurmasz/mipsunit-munit/src/master/

You should have access (no need for an account). Let me know if you have any trouble.

**Comment by JW529** [comment]
I can download it, thanks very much
