### ISSUE TITLE
Improve handling of assertion messages in golang

### ISSUE THREAD

**Issue by hobovsky** [codewars/runner#222]
Currently, assertion messages emitted by golang reporter are presented as `<LOG::>`:

![image](https://user-images.githubusercontent.com/23709795/200678124-d1232b6b-3982-4319-85f8-3f9621aab52c.png)

It's probably a workaround for an issue of test output panel, which has been fixed and now the assertions can be a part of `<FAIL::>`.

**Comment by kazk** [comment]
Fixed
