### ISSUE TITLE
Add OCaml 5.0.0

### ISSUE THREAD

**Issue by suic86** [codewars/runner#223]
Please complete the following information:

- Name: OCaml
- Version: 4.14
- Release Note/Changelog: https://ocaml.org/releases/4.14.0

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by hobovsky** [comment]
Related: codewars/ocaml#4

**Comment by kazk** [comment]
Deployed OCaml 5.0 support. Please test and let us know.

@monadius Can you update OCaml templates in https://github.com/codewars/tmp-snippets ?

Also, we should figure out if anything can be done for backwards compatibility.

**Comment by monadius** [comment]
I created a PR with updated OCaml templates.

I am going to update all OCaml katas to 5.0 manually. I don't think that we need to do any automatic updates: It should be easy to update most existing OCaml katas.

**Comment by monadius** [comment]
All OCaml katas are updated. @kazk please check that I have not missed some kata. I also created a [PR](https://github.com/codewars/docs/pull/477) for documents.

**Comment by kazk** [comment]
Confirmed, thanks!
