### ISSUE TITLE
Improve feedback of failed assertions in LUA

### ISSUE THREAD

**Issue by hobovsky** [codewars/runner#235]
Messages from failed assertions are presented with `<LOG::>` instead of being a part of `<FAILED::>` :

![image](https://user-images.githubusercontent.com/23709795/216988338-06251969-95e3-43d9-bc3d-d6a1e3db7eb4.png)

Can this be improved, or maybe such behavior is caused by some quirks of LUA testing framework?

The issue seems to be similar to #222 but I am not sure it has the same cause.

**Comment by kazk** [comment]
I'm pretty sure it's the same reason as #222, working around https://github.com/codewars/codewars-runner-cli/pull/305#issuecomment-278226045 which doesn't exist anymore.

I'll create a repo for the reporter.

**Comment by kazk** [comment]
Created https://github.com/codewars/busted-codewars

You should be able to make changes and test locally with `luarocks`.

**Comment by kazk** [comment]
I'll close this when it's deployed.

**Comment by kazk** [comment]
Deployed. Thanks @hobovsky
