### ISSUE TITLE
Cannot submit in Nim if warning in the tests

### ISSUE THREAD

**Issue by sotolf2** [codewars/runner#240]
**Describe the bug**
Nim Tests don't let me submit passed tests because of warnings from the test harness

**To Reproduce**
Provide code to reproduce the behavior or a link to Kumite.
https://www.codewars.com/kata/56ed20a2c4e5d69155000301/nim

This is however a problem with many of the katas

Submitting code that passes all tests doesn't work because of warnings

````
/workspace/solution_tests.nim(47, 19) Warning: Number of spaces around '..<' is not consistent [Spacing]
/workspace/solution_tests.nim(34, 20) Warning: Deprecated since v0.18.0; use 'rand' instead; random is deprecated [Deprecated]
/workspace/solution_tests.nim(34, 26) template/generic instantiation of `random` from here
/opt/nim/lib/pure/random.nim(227, 14) Warning: Deprecated since v0.18.0; use 'rand' instead; random is deprecated [Deprecated]
/workspace/solution_tests.nim(52, 7) template/generic instantiation of `suite` from here
/workspace/solution_tests.nim(54, 18) Warning: Deprecated since v0.18.0; use 'rand' instead; random is deprecated [Deprecated]
/workspace/solution_tests.nim(52, 7) template/generic instantiation of `suite` from here
/workspace/solution_tests.nim(56, 17) Warning: Deprecated since v0.18.0; use 'rand' instead; random is deprecated [Deprecated]
/workspace/solution_tests.nim(52, 7) template/generic instantiation of `suite` from here
/workspace/solution_tests.nim(57, 17) Warning: Deprecated since v0.18.0; use 'rand' instead; random is deprecated [Deprecated]
Error: execution of an external program failed: '/workspace/tests '
````

**Expected behavior**
Tests to not have errors that makes passing the kata impossible

**Browser**
If applicable, please provide your browser information.

- OS: Linux
- Browser: Vivaldi 
- Version 5.7.2921.60 (

**Additional context**

**Comment by B1tsTM** [comment]
These kind of issues should be submitted on kata's "Discourse" section, not here. It is true that the kata doesn't work with version 1.6 selected, but it works fine with 1.0. If there is no issue open about it, you should request it to be fixed by opening one.

**Comment by kazk** [comment]
Please use the kata discourse to report this.
