### ISSUE TITLE
Test report breaks abrupty when Swift tests crash

### ISSUE THREAD

**Issue by hobovsky** [codewars/runner#244]
Result of an arithmetic overflow in Swift tests:

![image](https://user-images.githubusercontent.com/23709795/233488013-737bd3ae-d784-45ca-9f77-772ae91dc489.png)

When tests crash in Swift, test report leaves no feedback about the crash. Maybe it would be possible to have a crash dump, or anything, presented in such situation?

**Comment by kazk** [comment]
Can you try with 5.9?

**Comment by hobovsky** [comment]
With 5.9, a core dump is there. It's not very helpful, but it's an issue with the runtime and not the CW runner. I will close this one as resolved and open a new one for specific problems, if any occur.
