### ISSUE TITLE
CW-233: Add Factor 0.99

### ISSUE THREAD

**Issue by Kacarott** [codewars/runner#258]
Factor 0.99 has [just been released](https://re.factorcode.org/2023/08/factor-0-99-now-available.html) and its a huge patch, finally catching back up with the development branch!

I fully expect many kata to be not initially compatible with the new version, but I'm excited to work on getting them all updated to 0.99.

**Comment by Kacarott** [comment]
As a side note, considering the breaking nature of many of these changes, and the already low solve count of many Factor translations, it will be a shame to lose many of the solutions that we do have. Perhaps it might be worth considering [this idea](https://github.com/codewars/codewars.com/discussions/3034)?

**Comment by nomennescio** [comment]
Please align this with me, as the test framework (https://github.com/codewars/testest) needs to support both 0.98 and 0.99, as there are major incompatibilities (renaming of common words). See also #166 for some further details.

**Comment by Kacarott** [comment]
It seems to me that testest simply needs to be updated to `0.99` and a new release made. The old version will just stay on the previous release.

Solutions will only not be lost if the kata tests do not require breaking changes. A kata can support multiple version, but it cannot support multiple versions of test code. And the test code should be updated, otherwise `0.99` will not be available for solvers, which defeats the point.

**Comment by nomennescio** [comment]
To clarify, just like e.g. Python, I want to have a dropdown box to be able to select a language version
![image](https://github.com/codewars/runner/assets/24315005/2ef3040d-330b-48d7-80d7-8d8d0c2f1a32)

From a maintenance point of view I want to be able to share code between different versions of `testest`, the supporting vocabularies and the Dockerfile. I'm not sure how this is done for Python, if e.g. version info is passed as argument to a Dockerfile, which could be made to work. I would like to hear such details (see also the discussion at #166  )

**Comment by Kacarott** [comment]
Yes, this is how adding a new language version works, it is simply added to the dropdown menu. A language version is only ever removed from this dropdown if it is manually removed (due to being outdated and no more kata relying on it).

As far as I know, Python (and all langs) merely have a seperate dockerfile for each language version. The dockerfile can then simply access the relevant version or branch of `testest`, which includes supporting vocabularies.

I did read through #166, however what I understood from it was that you wanted to add some kind of patch system to be able to change the configuration of the `testest` vocab in the event that it was added to the Factor library. To my knowledge, `testest` did not make it into 0.99, and so that is not a concern, is it? There is also no reason for the `testest` interface to change between versions, is there? It's implementation merely needs to be updated to 0.99, but the interface used by authors remains the same.

**Comment by nomennescio** [comment]
If it's not by an argument from the environment, but a new Dockerfile is what it takes, that is fine by me (I wrote large parts of the Dockerfile anyway). I want to however share code between versions, so a simple copy of the complete `testest` codebase is not desirable. (The details in #166 about patching are not relevant to this discussion, as I can always refactor that code to support multiple versions.)

**Comment by nomennescio** [comment]
Maybe it is like @kazk already mentioned in #166?
```
docker build --no-cache --progress=plain --build-arg FACTOR_VERSION=0.99 -t factor:latest .
```
With FACTOR_VERSION being either 0.98 or 0.99 being available as build argument to a single Dockerfile? That would probably be enough.

**Comment by VanessaGreene** [comment]
Escalated to CW_172.

**Comment by nomennescio** [comment]
> Escalated to CW_172.

Where can we see this issue, and how to integrate an update to the `testest` framework.

**Comment by kazk** [comment]
I think having the Dockerfile in the test framework repository is confusing you guys. I'll create a new repository for the container image like Forth.

After creating the new repository https://github.com/codewars/factor, we can add Factor 0.99 like this:

1. Update `testest` to work with Factor 0.99. Note that there's no need to make this backwards compatible.
2. Release the new `testest` version
3. Update the Dockerfile to use Factor 0.99 and the new `testest`
4. Push the new image
5. Add Factor 0.99 support to the runner
6. Enable Factor 0.99 on Codewars

Factor 0.98 is unaffected and will be supported until every kata is updated to 0.99.

I'll give you guys `write` permission and set up some workflows, so you'll be able to complete the steps 1-4 without me.

**Comment by kazk** [comment]
Created https://github.com/codewars/factor and gave both of you `write` permission. You can build and push a new image by creating a new release with a tag formatted like `${FACTOR_VERSION}-v${TESTEST_VERSION}`. The format actually doesn't matter, but let's follow this. Forth is now maintained the same way, so @nomennescio should know.
I've also removed Docker related files from the testest repo.

You should be able to finish the steps 1-4 with this setup. Let me know if you have any questions.

**Comment by nomennescio** [comment]
@kazk I released version 2.1 of the testest framework, which should work with both Factor 0.98 and 0.99. I removed the deprecated `lf` word, but as far as I know no Kata uses that. Can you can deploy this, and check if all katas keep running?
Then the next step to move to 0.99 will be quite trivial.

I noticed that currently some dynamic .so libraries are missing from 0.98, I'll try to add these to the 0.99 version.

**Comment by nomennescio** [comment]
Released a new version of the factor runner with `testest` v2.1 and Factor 0.98

**Comment by kazk** [comment]
I'll check the compatibility against all published kata and will let you know.

**Comment by kazk** [comment]
I checked locally and `lf` is used.

[Count the smiley faces!](https://www.codewars.com/kata/583203e6eb35d7980400002a/factor)
```text
/workspace/kata/tests/tests.factor

28:         [ "Test Failed for input :" write lf mine pprint lf error. ]
                                                ^
No word named “lf” found in current vocabulary search path
```

[Detect Pangram](https://www.codewars.com/kata/545cedaa9943f7fe7b000048/factor)
```text
/workspace/kata/tests/tests.factor

54:         [ "Test Failed for input :" printf lf mine "%u" printf lf error. ]
                                                 ^
```

[Does my number look big in this?](https://www.codewars.com/kata/5287e858c6b5a9678200083c/factor)
```text
/workspace/kata/tests/tests.factor

6:     [ "Test failed for input :" printf lf input "%u" printf lf error. ]
```

[Find the anonymous function](https://www.codewars.com/kata/55a12bb8f0fac1ba340000aa/factor)
```text
/workspace/kata/tests/tests.factor

38:         [ "Test Failed for inputs :" printf lf mine1 "%u" printf lf mine2 "%u" printf lf error. ]
```

[First-Class Function Factory](https://www.codewars.com/kata/563f879ecbb8fcab31000041/factor)
```text
/workspace/kata/tests/tests.factor

28:         [
29:           "Test failed for inputs :" printf lf mine "%u" printf lf n "%u" printf lf
```

[Human Readable Time](https://www.codewars.com/kata/52685f7382004e774f0001f7/factor)
```text
/workspace/kata/tests/tests.factor

6:     [ "Test failed for input :" printf lf input "%u" printf lf error. ]
```

[Rock Paper Scissors!](https://www.codewars.com/kata/5672a98bdbdd995fad00000f/factor)
```text
/workspace/kata/tests/tests.factor

41:       [ "Test failed for inputs :" printf lf mine1 "%u" printf lf mine2 "%u" printf lf error. ]
```

[The Hashtag Generator](https://www.codewars.com/kata/52449b062fb80683ec000024/factor)
```text
/workspace/kata/tests/tests.factor

42:         [ "Test failed for input :" printf lf mine ... lf error. ]
                                                 ^
No word named “lf” found in current vocabulary search path
```

Can you remove `lf`? If not, we can keep 0.98 as is, add 0.99, deploy 0.99, update all compatible, manually update any incompatible, then remove 0.98.

**Comment by Kacarott** [comment]
I've removed `lf` from all those.

**Comment by kazk** [comment]
Confirmed. I'll let you know when the updated 0.98 is deployed.

**Comment by nomennescio** [comment]
> I've removed `lf` from all those.

Thanks a lot @Kacarott !

**Comment by kazk** [comment]
Deployed 0.98

**Comment by nomennescio** [comment]
> Deployed 0.98

Thanks very much @kazk and @Kacarott for your support. Onto the next step: activating Factor 0.99.

**Comment by nomennescio** [comment]
@kazk I released a new Factor 0.98 image where I bound (some) missing libraries, could you deploy that?

**Comment by kazk** [comment]
Next time, please create a new release instead of just tagging to document the changes. Also, please increment a tag instead of appending words so we know which is newer without looking up the date pushed. I understand it was awkward because we're using Factor and testest versions to tag the image, but just appending an incremental number like `0.98-v2.1-r1` is better than `0.98-v2.1-with-libraries`, `0.98-v2.1-with-report`, `0.98-v2.1-with-reporting`.

I'll let you know when the latest image is deployed.

**Comment by nomennescio** [comment]
> Next time, please create a new release instead
...
> I'll let you know when the latest image is deployed.

I'm not sure what you mean; I did create a new release. Github requires those tags for releases.

**Comment by Kacarott** [comment]
The confusion might come from the latest release having the exact same name as the release before it?

**Comment by nomennescio** [comment]
Might be; the naming convention Kazk choose was to have FACTOR-VERSION-TESTEST-VERSION, but that's only in the title and in the tags. The release labeled as "latest" would be the one that needs to be installed, which is also the most recent commit in the repo. I don't exactly understand the confusion.

**Comment by kazk** [comment]
Yeah, I saw the release "Factor 0.98 with Testest 2.1" and thought it was the previous one.
I wasn't confused which tag was the latest because I can see that on https://github.com/codewars/factor/pkgs/container/factor. But I was confused when I saw the tags `with-report` and `with-reporting` because I had no idea what "report" meant, so I went to read the pull requests. This is why I asked you to create a release note, but you did that. My bad :laughing:

For the tag convention, it's best practice to make the tag/version sortable in general, so let's just append numbers if we need to update the image with the same Factor and testest versions.

**Comment by kazk** [comment]
Deployed

**Comment by nomennescio** [comment]
> Yeah, I saw the release "Factor 0.98 with Testest 2.1" and thought it was the previous one. I wasn't confused which tag was the latest because I can see that on https://github.com/codewars/factor/pkgs/container/factor. But I was confused when I saw the tags `with-report` and `with-reporting` because I had no idea what "report" meant, so I went to read the pull requests. This is why I asked you to create a release note, but you did that. My bad 😆

Apologies accepted
 
> For the tag convention, it's best practice to make the tag/version sortable in general, so let's just append numbers if we need to update the image with the same Factor and testest versions.

That's fine with me

**Comment by nomennescio** [comment]
I just released Factor 0.99

**Comment by kazk** [comment]
Yeah, I'll let you know when it's deployed.

**Comment by kazk** [comment]
Deployed. Looks like all kata were compatible.

By the way, I'll be on vacation next week. 0.98 is still available if there's any problem with 0.99.

**Comment by Kacarott** [comment]
So I don't know what happened, but `0.99` Codewars does not actually seem to be `0.99`. It looks to me like its just another `0.98`.

The fact that all kata were compatible should be a big red flag about this, there should *definitely* be kata tests which break for the real 0.99.

**Comment by kazk** [comment]
Ugh, looks like the latest tag on https://github.com/codewars/factor/pkgs/container/factor is still `0.98-v2.1-r1.1`, and I blindly copy pasted it :man_facepalming:

![image](https://github.com/codewars/runner/assets/639336/4b88daf5-e9c3-4d56-8bf7-1edc7cc43272)

**Comment by kazk** [comment]
Reverted the language update for kata, and I'll deploy the correct image soon.

**Comment by nomennescio** [comment]
Well, not sure what you were looking at, but after I released 0.99, I did some more work, which triggered some workflow runs

![image](https://github.com/codewars/runner/assets/24315005/7986395f-28c3-4d21-b41f-8510a428ed61)

However, in releases you will see the actual latest release

![image](https://github.com/codewars/runner/assets/24315005/c82e14c3-b973-4040-9869-1b0ad9022a2f)

which IS Factor 0.99

![image](https://github.com/codewars/runner/assets/24315005/bdf3dcb4-5dfb-466e-ad25-d1d96d388db5)

**Comment by kazk** [comment]
As I commented above, I look at https://github.com/codewars/factor/pkgs/container/factor for the container images pushed.

![image](https://github.com/codewars/runner/assets/639336/58d0b2b8-be51-4802-bd13-abc12968ddc1)

And was confused because the image with 0.98 was pushed mostly recently for some reason, and marked as "latest" there.

By the way, the [latest release](https://github.com/codewars/factor/releases/tag/0.99-v2.1-release-1.0) you mentioned has a tag `0.99-v2.1-release-1.0`, but `0.99-v2.1-r1.0` is newer, so I updated to that (compared the git tags and there's no difference).

**Comment by Kacarott** [comment]
Nice, that seems better. Do you have a list of kata that need updating?

**Comment by kazk** [comment]
We have 125 incompatible kata. https://www.codewars.com/kata/search/factor?outdated=true

**Comment by Kacarott** [comment]
Nice, thanks!

**Comment by nomennescio** [comment]
> As I commented above, I look at https://github.com/codewars/factor/pkgs/container/factor for the container images pushed.
> And was confused because the image with 0.98 was pushed mostly recently for some reason, and marked as "latest" there.

Right, the latest push is not the latest release.

> By the way, the [latest release](https://github.com/codewars/factor/releases/tag/0.99-v2.1-release-1.0) you mentioned has a tag `0.99-v2.1-release-1.0`, but `0.99-v2.1-r1.0` is newer, so I updated to that (compared the git tags and there's no difference).

No problem. The `0.99-v2.1-release` is the tag Github creates for a release, the `0.99-v2.1-r1.0` tag is an annotated tag I created, pointing to the same commit.

**Comment by nomennescio** [comment]
> We have 125 incompatible kata. https://www.codewars.com/kata/search/factor?outdated=true

B.t.w. what is the issue here? Those ones keep running on 0.98 right? Is it a policy Codewars want to make all katas work with the latest released version? I'm not familiar with how this is typically handled, as I actually don't understand how the version selection works in Codewars.

**Comment by Kacarott** [comment]
It just means that 0.99 is not available for the 125 kata, because the tests are not compatible. And yes ideally all kata should be updated so that the latest version is available to solvers.

But 0.99 is already available on all other kata, and for new kata/translations.

**Comment by nomennescio** [comment]
> It just means that 0.99 is not available for the 125 kata, because the tests are not compatible. And yes ideally all kata should be updated so that the latest version is available to solvers.
> 
> But 0.99 is already available on all other kata, and for new kata/translations.
> 
> I'm working on updating the tests for the 125 kata, I updated about 30 this morning and will try finish the rest throughout this weekend.

Great job! Thanks for doing that

**Comment by Kacarott** [comment]
Alright, all 125 kata are updated to 0.99

**Comment by Kacarott** [comment]
One kata (so far) has been found which was incompatible with 0.99, and yet 0.99 was still active on it. I wonder if this might be because of another 0.98 being added under the label of 0.99 which all kata were automatically compatible with, and then removed. Perhaps not all kata had 0.99 fully been removed before the actual 0.99 version was added?

In any case, it might be good to do a proper check of each factor kata to see if the reference solution passes the tests, if that is possible.

**Comment by kazk** [comment]
Looks like there are some failing with `Vocabulary does not exist name "math.ranges"` error, and a few failing random tests. Not sure what happened with the former.

> Perhaps not all kata had 0.99 fully been removed before the actual 0.99 version was added?

This shouldn't be possible because I had removed `0.99` from every kata literally with a database command before I deployed the fix :/

[Convert a String to a Number!](https://codewars.com/kata/544675c6f971f7399a000e79)
```
/workspace/string-to-number/tests/tests.factor

4: USING: string-to-number tools.testest random math math.ranges math.parser locals ;
                                                                ^
Vocabulary does not exist
name "math.ranges"
```

[Delta Generators](https://codewars.com/kata/6040b781e50db7000ab35125)
```
<FAILED::>Test Failed : Expected :<:LF:>{<:LF:>    918064293+202440859607896322249/366625676974614441300<:LF:>    -1546938552-802634820530861862107/2884765195142360998650<:LF:>    2007250188+1113404249527729747083253/1808747777354260346153550<:LF:>    -2485242137-193727162149282591692367/602915925784753448717850<:LF:>    3222071015+2765726331746406894763/27405269353852429487175<:LF:>    -4419736953-3177760493859397200296/4327147792713541497975<:LF:>    6126191854+22648021255990776039/106843155375642999950<:LF:>    -8122258616-118708367338515558503/263353939736720043120<:LF:>    9875042198+379319193011526653849/438923232894533405200<:LF:>    -10650627776-38918272220148923989/54865404111816675650<:LF:>    9818222277+2627952061150513871/493788637006350080850<:LF:>    -7224145003-471428103936756711327/1591096719242683593850<:LF:>    3390867910+12430823205504180888592/14797199488956957422805<:LF:>    644027112+293172060855840050562362/488307583135579594952565<:LF:>    -3792054390-1410474609732371578665833/2101202327431887954038310<:LF:>    5396032444+6840792354167613000853/9261961771889708473020<:LF:>    -5438295772-12004561504218580261/60972162134697140418<:LF:>    4399043490+13132791202407854596049/18088408099960151657340<:LF:>    -2926411819-2453643363800617984708/4522102024990037914335<:LF:>    1548279803+11414705239049867454131/27132612149940227486010<:LF:>}<:LF:>But got :<:LF:>{<:LF:>    6510409897+1182618341939/2909253166300<:LF:>    -5322328272-82139023858922551/87242683951004400<:LF:>    3594668582+107994991082441497327/118999020909170001600<:LF:>    -1864606145-23037504199269487729/39666340303056667200<:LF:>    548141160+151345398697193293/190703559149310900<:LF:>    147591579+169975195355089/752092103025900<:LF:>    -264587205-149592352815939/157103683743188<:LF:>    81375888+8736264240590863/10436173277226060<:LF:>    -49085694-7113039694943137/12175535490097070<:LF:>    714422300+1011126598075395/61724671223709494<:LF:>    -2689728027-476944167026349/905053830259670<:LF:>    6678137407+5754338195914729/13575807453895050<:LF:>    -13445033005-8236700461483832033/11548486874113389200<:LF:>    23561472351+836240105229322401833/935427436803184525200<:LF:>    -36872512658-1883321928562257691/2784010228580906325<:LF:>    51953434342+2965276885989899119/7795228640026537710<:LF:>    -66051370019-4808349085791220919/21259714472799648300<:LF:>    75844558650+1896102642777317/5799158339552550<:LF:>    -78776991946-4253810166300521/4619668507779150<:LF:>    74196725177+4255420797581837/25967399822674380<:LF:>}
```

[Find the missing letter](https://codewars.com/kata/5839edaa6754d6fec10000a2)
```
/workspace/kata/tests/tests.factor

4: USING: tools.testest locals kernel math.ranges math strings sequences sets random ;
                                                 ^
Vocabulary does not exist
name "math.ranges"
```

[Fractran Interpreter](https://codewars.com/kata/5ebae674014091001729a9d7)
```
/workspace/fractran/tests/tests.factor

1: USING: fractran tools.testest kernel math math.functions locals random math.parser splitting sequences math.ranges arrays formatting ;
                                                                                                                     ^
Vocabulary does not exist
name "math.ranges"
```

[Invert values](https://codewars.com/kata/5899dc03bc95b1bf1b0000ad)
```
/workspace/invert/tests/tests.factor

1: USING: invert tools.testest kernel sequences math math.ranges random locals ;
                                                                ^
Vocabulary does not exist
name "math.ranges"
```

[Odd Ones Out!](https://codewars.com/kata/5d376cdc9bcee7001fcb84c0)
```
/workspace/odd-ones-out/tests/tests.factor

1: USING: odd-ones-out tools.testest kernel locals math sequences random math.ranges ;
                                                                                    ^
Vocabulary does not exist
name "math.ranges"
```

[Rotate for a Max](https://codewars.com/kata/56a4872cbb65f3a610000026)
```
/workspace/max-rot/tests/tests.factor

4: USING: max-rot tools.testest random math
                 ^
/workspace/max-rot/max-rot.factor

1: USING: kernel math.ranges locals math.parser
                            ^
Vocabulary does not exist
name "math.ranges"
```

[Sum of array singles](https://codewars.com/kata/59f11118a5e129e591000134)
```text
<FAILED::>Test Failed : Expected :<:LF:>7490<:LF:>But got :<:LF:>0
```

[Take a Ten Minutes Walk](https://codewars.com/kata/54da539698b8a2ad76000228)
```text
/workspace/kata/tests/tests.factor

1: USING: arrays assocs assocs.extras combinators.short-circuit debugger io kernel
2: locals math math.combinatorics math.ranges math.statistics prettyprint qw random sequences
                                             ^
Vocabulary does not exist
name "math.ranges"
```

[The Bee](https://codewars.com/kata/6408ba54babb196a61d66a65)
```text
/workspace/the-hive/tests/tests.factor

1: USING: tools.testest kernel sequences random math.ranges assocs locals formatting preloaded ;
                                                           ^
Vocabulary does not exist
name "math.ranges"
```

**Comment by Kacarott** [comment]
Thanks for that list. I've fixed all the `math.ranges` ones. The other two I'll have to look at closer as they only fail sometimes, and the reason doesnt seem related to 0.99 anyway.
