### ISSUE TITLE
Certain Rust code consistently causes 500 error

### ISSUE THREAD

**Issue by ggorlen** [codewars/runner#259]
**Describe the bug**

Specific Rust code consistently causes a 500 error in a certain kata.

**To Reproduce**

Go to [Fix the match error](https://www.codewars.com/kata/64e9f837f1294f9097435483/rust) kata, paste in the following code:

```rust
fn is_even(even_or_odd: String) -> bool {
    match even_or_odd {
        even => true,
        odd => false,
        _ => {panic!("Invalid Input")}
    }
}
```

Observe the issue:

```
Server Execution Error:

Internal Server Error

Request Error:
Request failed with status code 500

This error was caused due to an issue processing the web request, not because of an issue executing your code. You can retry the request.
```

**Expected behavior**

I expect the server to handle the code without causing an internal error, and instead return a Rust compiler error.

**Browser**

Probably not applicable, but can't hurt:

- OS: Ubuntu 22.04
- Browser Firefox
- Version 116.0.3 (64-bit)

**Comment by Blind4Basics** [comment]
('updated the link so that it doesn't point to the trainer)

**Comment by kazk** [comment]
Fixed. The failure event from the `should_panic` test doesn't have the `stdout` field, so the server was failing to post process the test outputs.
