### ISSUE TITLE
Java: cannot detect class name of enum

### ISSUE THREAD

**Issue by Madjosz** [codewars/runner#274]
Similar to #186 Java runner cannot detect the class name if the top level structure is an `enum`.

Following code should result in a source file named `A.java`:
```java
enum A {}
```

Currently execution fails with
> Server Execution Error:
```
Failed to detect class name:
enum A {}
```
> Request Error:
```
Request failed with status code 422
Please fix the issue and try again.
```

Happens in all supported Java version (8, 11, 17).

**Comment by kazk** [comment]
Deployed a fix

**Comment by Madjosz** [comment]
Confirmed fixed.
