### ISSUE TITLE
Setup of Reason language needs a review and a major update.

### ISSUE THREAD

**Issue by hobovsky** [codewars/runner#278]
**Disclaimer:** I am not very familiar with the Reason ecosystem itself, and the post below describes things which I discovered when authoring Reason translations for CW kata. Following information is written from perspective of a Codewars translator rather than active user of the Reason language or a member of the Reason community.

In August 2020, Reason ecosystem went through a major change and the language, runtime, and tooling split: Reason the language went one way, and BuckleScript the "JS bridge" went another way (and turned into ReScript).

Some history:
- https://rescript-lang.org/blog/bucklescript-is-rebranding
- https://melange.re/v2.2.0/rationale/#a-bit-of-history

Since the split, each of the paths piled up its own updates, improvements, etc. and the differences started to grow.

As a result, any currently materials related to Reason or BuckleScript do not describe anything close to what CW's setup of Reason is. It's difficult to find any documentation related to BuckleScript and its APIs, because it's not related to Reason anymore. Searching for Reason leads to results which are not related to CW's Reason.

On top of that, currently the output of compilation and runtime errors is confusing and not very helpful with diagnosing problems with the author's/translator's code. Maybe the new version improved in this area?

Problematic part would be to decide what to update to: to rebranded version of ReasonML, or to ReScript? I do not know what would be required to go any of these ways, and I do not know which one is easier, more helpful, or more convenient. ReScript was advertised to ensure backwards compatibility for some time, but I did not check if it actually has.

**Comment by error256** [comment]
https://github.com/codewars/runner/issues/153

**Comment by hobovsky** [comment]
🤦‍♂️ 

Closing as a duplicate of #153 .
