### ISSUE TITLE
Remove TypeScript 4.2

### ISSUE THREAD

**Issue by hobovsky** [codewars/runner#280]
Since the list of [TypeScript kata to update](https://github.com/codewars/content-issues/wiki/List-of-TypeScript-Kata-to-Update) has been cleared and there's no [outdated TypeScript kata](https://www.codewars.com/kata/search/typescript?q=&order_by=sort_date%20desc&outdated=true), TypeScript 4.2 can be removed.

**Comment by kazk** [comment]
Removed. Thanks!
