### ISSUE TITLE
Add SPARQL

### ISSUE THREAD

**Issue by VirtueDevOps** [codewars/runner#293]
Please complete the following information about the language:

- Name: SPARQL
- Website: https://www.w3.org/TR/sparql11-query/
- Language Version: 1.1

The following are optional, but will help us add the language:

- Test Frameworks: Testing in SPARQL often involves running queries against a known RDF dataset and checking if the results match expected outputs. You can create test cases where specific SPARQL queries should return known results or perform certain transformations.
- How to install: SPARQL itself is a query language and does not require installation. However, to run SPARQL queries, you need a SPARQL endpoint or a triplestore (RDF database).
Common triplestores include Apache Jena Fuseki, OpenLink Virtuoso, and RDF4J. These can be installed on a server or used as part of a local development environment.
Installation usually involves downloading the software package and following the specific setup instructions for the chosen system.
- How to compile/run: To run a SPARQL query, you generally need to connect to a SPARQL endpoint through a web interface, command line tool, or programmatically using libraries available in various programming languages (e.g., Python, Java).
The query is then executed by the triplestore, which processes the query and returns the results.
- Any comments: (e.g., what's interesting about this language): SPARQL is unique in its ability to query data across diverse and distributed data sources as long as they conform to the RDF standard.
It's particularly powerful for querying complex relationships and can perform sophisticated queries over graph data.
SPARQL supports a variety of functions, including aggregation, subqueries, and federated queries, allowing for versatile and powerful data manipulation and analysis.
It's widely used in semantic web technologies, linked data projects, and for integrating data from different domains and sources.

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by hobovsky** [comment]
Could you transfer all this information to #255 ?

I am going to close this one as a duplicate, but this info could be useful in the original ticket.

**Comment by VirtueDevOps** [comment]
Am i able to add this content to the #255? I feel like if i add it to the
comments it will get lost in the sauce so to speak


J.G. McLellan
