### ISSUE TITLE
Add Coq 8.12

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/runner#3]
Please complete the following information:

- Name: Coq
- Version: 8.12
- Release Note/Changelog: https://coq.github.io/doc/v8.12/refman/changes.html#version-8-12

---

:+1: reaction _might_ help.

**Comment by kazk** [comment]
Deployed. We have 2 kata to update: https://github.com/codewars/codewars.com/wiki/List-of-Coq-Kata-to-Update
