### ISSUE TITLE
Setting random seed automatically in the Lua output handler

### ISSUE THREAD

**Issue by slashOwO** [codewars/runner#312]
**Is your feature request related to a problem? Please describe.**
In Lua, `math.random()` always generates the same number if a random seed is not set.

**Describe the solution you'd like**
Add `math.random(os.time())` to the Lua output handler.

**Comment by hobovsky** [comment]
Related: https://www.codewars.com/kumite/66854a3e1939adaa91ba1923?sel=66854a3e1939adaa91ba1923#6688340c51371d9f8ab7e87e

**Comment by hobovsky** [comment]
Codewars uses Busted in pretty much normal way, and does no custom things when running Busted tests except using the [Codewars reported for Busted](https://github.com/codewars/busted-codewars/tree/main/src/busted/outputHandlers). So the expectation is that Busted tests run on CW behave pretty much the same as Busted tests run outside of CW. It is true that CW output handler does not set the random seed, but:
- It's not something what a test reporter should do. Controlling the environment and setting the global value of the seed is not something what should be done by a reporting utility. The file in the [busted](https://github.com/lunarmodules/busted) repository you linked is not a source code of an output handler, but code of the runner itself, which on CW works the same way.
- I skimmed through the sources of the `busted` runner and I actually cannot see how and where it sets the global random seed. As far as I see (but I might have missed something), it does so only when the `-shuffle-files` or `-shuffle-tests` option is used, and random seed is seeded only when you request a random order of tests with command line (which CW does not do, and also is not related to logic of generating inputs).

Can you please make double sure that outside of CW, when no additional command line parameters are used, the random seed is set by the runner?
