### ISSUE TITLE
Add [language name]

### ISSUE THREAD

**Issue by boricsk** [codewars/runner#320]
Please complete the following information about the language:

- Name: SQL
- Website: https://www.microsoft.com/en-us/sql-server/sql-server-2022
- Language Version: T-SQL 2022

The following are optional, but will help us add the language:

- Test Frameworks:
- How to install:
- How to compile/run:
- Any comments: (e.g., what's interesting about this language)

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by hobovsky** [comment]
Would you mind filling in the placeholders in the title, and the missing relevant information in the post?

**Comment by hobovsky** [comment]
Closing due to missing relevant information.
