### ISSUE TITLE
C++: Update snowhouse to 4.0+

### ISSUE THREAD

**Issue by kazk** [codewars/runner#35]
This version changes the output for boolean and strings that's been confusing our users.

https://github.com/banditcpp/snowhouse/releases/tag/v4.0.0

We're currently using v3.1.1. https://github.com/codewars/igloo/commit/abac06d6df21065acc16fccf5fefd10493c3580a

---

- [x] Make our fork work with snowhouse v4+
- [x] Check compatibility with existing kata

**Comment by hobovsky** [comment]
What kind of help specifically is wanted here?

**Comment by kazk** [comment]
Any help to make [our fork](https://github.com/codewars/igloo) work with snowhouse 4.0+. It's using v3.1.1 at the moment. I'm not sure how much effort is required because I haven't tried yet.

To build the project locally:
```bash
git clone --recursive --depth 1 --branch codewars https://github.com/codewars/igloo.git
mkdir -p igloo/build
cd igloo/build
cmake -GNinja ..
# ninja install
```

Currently, the submitted solution is concatenated like the following:

```cpp
#include <igloo/igloo_alt.h>
#include <igloo/CodewarsTestListener.h>

using namespace igloo;

// #include "preloaded.h" if preloaded

// [solution]

// [tests]

int main(int, const char *[]) {
  NullTestResultsOutput output;
  TestRunner runner(output);
  CodewarsTestListener listener;
  runner.AddListener(&listener);
  runner.Run();
}
```
This doesn't need to remain the same.

**Comment by hobovsky** [comment]
I checked out the https://github.com/codewars/igloo/tree/codewars-snowhouse-5, filled in the template with contents of randomly picked kata ([Bug's Life](https://www.codewars.com/kata/5b71af678adeae41df00008c/forks/cpp)) and it run for me flawlessly in my VS 2019. `bool` stringizer works, got no compilation problems. I am not sure what kind if further help you'd need here, but just let me know.

If we'd be able to get Snowhouse updated, I'd think on some improvements, like providing a function or macro being able to work with custom assertion messages, or custom assertion criteria (fuzzy equals?), some commonly needed, but missing stringizers, or something like that.

On the other hand, I find both Igloo and Snowhouse not that great frameworks to work with. Igloo lacks things like fixtures, parametrized test cases, descriptions of contexts, and Snowhouse is not too rich into assertions and their capabilities either. As much as I prefer C++ over C, I think Criterion is much better :( Unless I am missing something.

**Comment by kazk** [comment]
> I checked out the https://github.com/codewars/igloo/tree/codewars-snowhouse-5

Wait, I did that? I guess I was planning to check the compatibility against existing kata and had completely forgotten about it. :man_facepalming:

> If we'd be able to get Snowhouse updated

Are you thinking of adding features to Snowhouse? You can contribute upstream or maintain our fork.

> On the other hand, I find both Igloo and Snowhouse not that great frameworks to work with.

Igloo is abandoned too. But we're stuck for now because of the existing kata and the Codewars' current limitation of one test framework per language for kata. The runner supports more (Criterion, Google Test) and I remember I liked https://github.com/catchorg/Catch2.

**Comment by hobovsky** [comment]
> Are you thinking of adding features to Snowhouse? You can contribute upstream or maintain our fork.

I was thinking not as much about adding features to the framework, but maybe rather about providing some snippets, examples, and classes supporting C++ kata authors strictly in context of Codewars. But now as you suggested it... why not? I do not feel confident enough to contribute anything what would serve a general public, that's why I'd prefer stay in scope of CW, but if anything good comes out of it, then maybe it would be worth a shot :)

**Comment by kazk** [comment]
I forked snowhouse under Codewars. https://github.com/codewars/snowhouse

We can update Igloo to use that if the community adds features and maybe open PRs upstream with them.

**Comment by kazk** [comment]
Deployed
