### ISSUE TITLE
Add `System.CodeDom` assembly to C# 8.0

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/runner#37]
As I noted on https://github.com/codewars/codewars.com/wiki/List-of-C-Sharp-Kata-to-Update a few hours ago, `CSharpCodeProvider` and `CodeDomProvider` is now in a different assembly, so the new assembly should be added.

(I don't think adding the assembly alone will make those kata work since CodeDom has basically been deprecated in flavor of roslyn in newer .NET Core versions, but at least it should solve part of the problem.)

---

https://www.nuget.org/packages/System.CodeDom

**Comment by kazk** [comment]
Deployed
