### ISSUE TITLE
Support Factor 'extra' libraries

### ISSUE THREAD

**Issue by nomennescio** [codewars/runner#40]
Please support the 'extra' libraries in Factor, currently they are not in the vocabulary search path.

**Comment by nomennescio** [comment]
Running this code inside Factor:
`vocab-roots get .`
prints
```
V{
    "resource:core"
    "resource:basis"
    "resource:extra"
    "resource:work"
    "/workspace"
}
```
So this strongly suggests that the correct "extra" vocabulary root **is** defined, however vocabularies inside extra are not found. E.g.

`"sequences.extras" vocab-source-path .` should print `resource:extra/sequences/extras/extras.factor`, but instead `f` is printed, indicating it is not found.

This suggest an issue with the installation of the Factor distribution in the Codewars context.

**Comment by nomennescio** [comment]
Yup, found an issue which shows the Factor installation is not correct. Just execute `load-all`. This should just load all vocabularies present in the Factor tree. However, on Codewars this fails with: 
```
resource:basis/english/english.factor

3: USING: accessors arrays assocs assocs.extras combinators
                                               ^
Vocabulary does not exist
name "assocs.extras"
```

**Comment by kazk** [comment]
I had removed `extras` because I thought it was example programs. It has stuff like `99-bottles` and `game-of-life` and also adds 40 MB.

Do we need all of them?

**Comment by nomennescio** [comment]
Ah, that explains it! The `resource:extra` root points to the `extra` subdirectory.

I couldn't tell you which ones are needed straight away, so the quickest way is to include everything. If you need to know in more detail, you can check which `.factor` files outside `extra` refer to vocabularies (mapped onto subdirectories and files) inside the `extra` directory.

**Comment by nomennescio** [comment]
For performance reasons, it might be interesting to create a new `factor` executable with many default libraries already loaded; those will be pre-compiled into the new executable. In the regular case, all required libraries are compiled each time a user runs a Kata. If you're interested, I can tell you more about it.

**Comment by nomennescio** [comment]
I've looked at filesizes: the size of my `extra` directory is 25MB. If I look at the top contributers, then the following can probably be safely removed:

- bunny
- images/testing
- usa-cities (it is a library, but probably not that useful)
- clutter
- gstreamer
- websites
- benchmark
- gpu
- snake-game

and everything else is way below 1 MB

**Comment by kazk** [comment]
Thanks! I also removed `project-euler`, `rosetta-code`, `audio/engine/test`, `talks`. I'll let you know when this is deployed.

---

I'm interested in creating a new `factor` executable, but let's discuss further in a separate issue. Can you open a new issue with details?

**Comment by kazk** [comment]
Deployed

**Comment by nomennescio** [comment]
Thanks, I just tested this in a Kata, and can confirm the vocabularies in 'extra' are now supported!

Can now do nice stuff like:
`: some-kata ( seq -- sum ) dup <odds> [ sq ] map-sum swap <evens> [ sqrt ] map-sum + ;`
