### ISSUE TITLE
Some Python code runs extremely slower inside a container since Docker 18.06.2

### ISSUE THREAD

**Issue by FArekkusu** [codewars/runner#58]
Something is wrong with the code runner (or is it CW?) when it comes to katas in Python, because it keeps getting slower. A few times in the last few months I've run into issues about the tests being impossible to pass because the user was left with less time than their solution could realistically run for. [This kata](https://www.codewars.com/kata/5765870e190b1472ec0022a2/discuss) is an example of this. Around a year ago I translated it to Python: the test generation + reference solution took 3.5 seconds. Today I had to change the tests because the original solution couldn't even reach the intensive cases.

**Comment by kazk** [comment]
Docker was updated multiple times since this issue was opened, and I'm pretty sure this is resolved. I get similar numbers inside container for https://github.com/codewars/runner/issues/58#issuecomment-519728553

Let me know if this is still an issue.
