### ISSUE TITLE
Duplicated output when multiple `It`s have the same name in C++

### ISSUE THREAD

**Issue by error256** [codewars/runner#64]
I'm not sure if it's the runner or output processing somewhere further.
https://www.codewars.com/kumite/5f4a84a44c2cc40010493e31
```cpp
Describe(function_foo) {
  It(should_return_zero) {
    Assert::That(foo(), Equals(0));
  }
};
Describe(function_bar) {
  It(should_return_zero) {
    Assert::That(bar(), Equals(0));
  }
};
Describe(function_baz) {
  It(should_return_zero) {
    Assert::That(baz(), Equals(0));
  }
};
```
The output of every failed `It` is duplicated with every following `It` with the same name:
![Example of output](https://user-images.githubusercontent.com/5375100/91641874-a6646980-ea16-11ea-99c2-e7dc8163ba81.png)

**Comment by kazk** [comment]
Deployed
