### ISSUE TITLE
Haskell GHC 8.2 formatting breaks in QuickCheck assertion

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/runner#65]
Try running the initial code on [this kata](https://www.codewars.com/kata/count-them-all/haskell):

![image](https://user-images.githubusercontent.com/14909989/57178512-d98afd00-6ea3-11e9-9464-14e628397e5b.png)

It seems that formatting breaks if a runtime error is triggered while doing QuickCheck testing.

**Comment by kazk** [comment]
When error happens inside QuickCheck, it catches it and reports it as a failure (`FailureReason Reason`). When it's not in QuickCheck, the error is directly reported (`FailureReason Error`).

So this is working as expected from test reporter point of view.
