### ISSUE TITLE
Add Ruby 3.0

### ISSUE THREAD

**Issue by kazk** [codewars/runner#7]
Please complete the following information:

- Name: Ruby
- Version: 3.0
- Release Note/Changelog:
  - https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/
  - https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/
  - https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/

---

:+1: reaction _might_ help.

**Comment by Steffan153** [comment]
At this point, 3.0? https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/

**Comment by Chrono79** [comment]
Any ETA for this?

**Comment by kazk** [comment]
I don't post ETAs here because the amount of time I can spend is unpredictable unless it's for Qualified customers. Most of the updates are done when I'm off work, so it depends on how much time I have and how motivated I am.

The priority roughly looks like this:

1. Requested by a major Qualified customer
2. Requested by multiple Qualified customers
3. Personal interest or clear demands

---

For Ruby, I know the users want it, and I've been wanting to add support as well. It's definitely on my list to do. The problem is that Ruby was one of the first few languages that was supported, so it's not in a good shape. I'd like to clean them up as much as I can when adding the next version to make it more maintainable, so it needs more effort/time compared to others.

For example, I've been wanting to get rid of the custom test framework. `minitest` can be "almost" a drop-in replacement, so I've been doing some experiments on and off. I also need to switch to using `Gemfile` and lockfile to manage packages, so the versions don't drift when rebuilding the image.

I'm expecting Ruby 2.7/3.0 to require manual updates, so I thought it was a good opportunity to swap the test framework, but I might give up on that for now because I don't think I have enough time. I'll try to find some time tomorrow.

**Comment by Chrono79** [comment]
Thanks for the explanation about what's involved in updating a language in CW, it's not so trivial as one could think.

**Comment by kazk** [comment]
>  it's not so trivial as one could think.

The languages I added or fixed are usually trivial. For example, Rust only takes like 30 minutes to add a new version. This is why I take time to clean up the old ones. It's much easier to maintain and update.

I worked on Ruby 3.0 support last night, and should be able to deploy it this week.

**Comment by kazk** [comment]
Deployed, but having some trouble updating existing kata.

I had assumed the following will fail to update:

```ruby
desctibe "bad group" do
  Test.assert_equals(add(1, 1), 2)
end
```
because no test case is detected.

However, apparently some authors wrote tests like this:
```ruby
desctibe "bad group" do
  Test.assert_equals(add(1, 1), 2)
end

describe "group" do
  it "test case" do
    Test.assert_equals(add(1, 2), 3)
  end
end
```
:man_facepalming: 

This is considered valid because there's at least one test case passing.

I reverted the automatic updates for now. I might need to compare the number of test cases between 2.5 and 3.0. This will fail for tests with varying number of tests, but it's a good start.

**Comment by kazk** [comment]
https://github.com/jonatas/fast might be useful to automate updates. It can at least be used to find invalid cases and prevent auto update.

**Comment by kazk** [comment]
I decided to check the test output structure before testing version compatibility instead. Ruby 3.0 is enabled in 740 kata now.

I also wrote a script to do mechanical fixes (e.g., global substitutions), and verify against the test. I can use these to update more automatically. Let me know if you find yourself doing trivial fixes.

**Comment by ejini6969** [comment]
@kazk Can you check gitter? (I PM you something ~~)
