### ISSUE TITLE
Add PureScript 0.13.8

### ISSUE THREAD

**Issue by reactormonk** [codewars/runner#8]
Please complete the following information:

- Name: PureScript
- Version: 0.13.8
- Release Note/Changelog: The biggest part is the removal of `Eff` in favor of `Effect`. It's also got a few more breaking changes: https://github.com/purescript/purescript/releases/tag/v0.13.0

---

- [ ] Update [reporter](https://github.com/codewars/purescript-spec-reporter-codewars) for `purescript-spec` v4.0

:+1: reaction _might_ help.

**Comment by kazk** [comment]
Superseded by #207
