### ISSUE TITLE
Add `libttb-dev` for <execution> header from c++17

### ISSUE THREAD

**Issue by jpm86** [codewars/runner#85]
**Describe the bug**
Including the `<execution>` header causes a solution to fail to compile with `fatal error: 'tbb/blocked_range.h' file not found`

**To Reproduce**
In a C++ solution, `#include <execution>` and attempt to compile.

**Expected behavior**
Since the library was added with C++17, I would expect it to be usable.

**Comment by kazk** [comment]
Looks like `libtbb-dev` needs to be installed separately.

**Comment by kazk** [comment]
Forgot to close this, but this was deployed. I confirmed that it compiles, but haven't tested anything further.
Please let me know with some example code if it's not usable.
