### ISSUE TITLE
Add DateTime module for Perl5

### ISSUE THREAD

**Issue by suic86** [codewars/runner#86]
Please complete the following information about the package:

- Package name: DateTime
- Language name: Perl5
- Website: https://metacpan.org/pod/DateTime

Following are optional, but will help us consider adding:

- Why is this useful? It provides DateTime object implementation for Perl5.
- Example Code: See [here](https://metacpan.org/pod/DateTime#SYNOPSIS)
---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
Deployed
