### ISSUE TITLE
Add Scala 3

### ISSUE THREAD

**Issue by oybek** [codewars/runner#89]
Please complete the following information about the language:

- Name: Scala 3
- Website: https://dotty.epfl.ch/
- Language Version: 3.0

The following are optional, but will help us add the language:

- Test Frameworks: https://www.scalatest.org/user_guide/migrating_to_30
- How to install: https://dotty.epfl.ch/#getting-started
- How to compile/run: https://dotty.epfl.ch/#getting-started
- Any comments: (e.g., what's interesting about this language) the new version of scala, with a lot of improvements and new syntax

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
Scala 3 was deployed on Monday, so I'll close this.

For existing kata, I still need to write some script to update. If anyone is interested to help, implement the following method (Ruby):

```ruby
# Translate tests to ScalaTest 3.1+ complatible
def update_tests(test_code)
  # e.g., replace usage of org.scalatest.FunSpec to org.scala.funspec.AnyFunSpec
  test_code
end
```
I can call this for each kata, run tests using Scala 3, then update the kata if it's compatible.

**Comment by kazk** [comment]
Created https://github.com/codewars/content-issues/wiki/List-of-Scala-Kata-to-Update
