### ISSUE TITLE
Add Rust v1.49

### ISSUE THREAD

**Issue by ffred** [codewars/runner#92]
Please complete the following information:

- Name: Rust
- Version: Latest stable v1.49
- Release Note/Changelog: https://github.com/rust-lang/rust/blob/master/RELEASES.md

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
I'll wait for 1.49 since it's coming out soon. I won't update every 6 weeks, but I'd like to support decently up-to-date Rust. Maybe every 18 weeks.

**Comment by ffred** [comment]
Ok, great.. thanks !

**Comment by kazk** [comment]
Deployed Rust 1.49 support. I ran a script to update compatible kata and there are [305 incompatible ones](https://github.com/codewars/codewars.com/wiki/List-of-Rust-Kata-to-Update-to-1.49) :(

**Comment by imjasonmiller** [comment]
I think @Steffan153 and I managed to get all of them @kazk? :-)

**Comment by kazk** [comment]
Yes, thank you guys! There was one translation that was approved after the list was created, but I handled that.
