### ISSUE TITLE
Add PowerShell 7.1

### ISSUE THREAD

**Issue by suic86** [codewars/runner#96]
Please complete the following information:

- Name: PowerShell
- Version: 7.1 (replace 6.0 with this version)
- Release Note/Changelog: https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0 ([see also](https://devblogs.microsoft.com/powershell/announcing-powershell-7-1/))

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment]
PowerShell 7.2 was added a while ago for Qualified and I forgot to announce/document it.

**Comment by hobovsky** [comment]
You can use the `outdated` URL param: https://www.codewars.com/kata/search/powershell?q=&order_by=sort_date%20desc&outdated=true

Interesting fact: looking at results, there's only one Powershell kata compatible with PS7 :)

**Comment by kazk** [comment]
Yeah, it's been on my list to do. I'll try creating some time later today.

**Comment by kazk** [comment]
I did the following and most of them failed to update, unfortunately.

- Add `BeforeAll` to sample tests and test it with PowerShell 7.2
- Add `BeforeAll` to submission tests and test it with PowerShell 7.2
- If both passed, save the changes and set the version to 7.2

Also, https://www.codewars.com/kata/515de9ae9dcfc28eb6000001/powershell "passed", but it only ran the fixed tests for some reason, so I had to revert that. Please be careful when updating and make sure you see the correct test results. If you find the cause of this, please let me know.

**Comment by 4500zenja1** [comment]
Hey @kazk, so I think I found the solution how to bypass the problem with updating to PowerShell 7.2: you just need to move ALL helper functions to the BeforeAll — then the tests will start working normally.

I realised it by checking the official [Pester Guthub](https://github.com/pester/Pester), where the function for the checking has been put INTO the BeforeAll, smth like that:

```
# Before, tests can't find fixed function D:
BeforeAll {
  . $PSCommandPath.Replace('.Tests.ps1', '.ps1')
}

function testing($st, $we, $n, $expect) 
{
    $ans = rank $st $we $n
    $ans | Should -Be $expect
}

function fixed()
{
    testing "Addison,Jayden,Sofia,Michael,Andrew,Lily,Benjamin" @(4, 2, 1, 4, 3, 1, 2) 4 "Benjamin" 
    testing "Addison,Jayden,Sofia,Michael,Andrew,Lily,Benjamin" @(4, 2, 1, 4, 3, 1, 2) 8 "Not enough participants"
    testing "" @(4, 2, 1, 4, 3, 1, 2) 6 "No participants"
    testing "Addison,William,Jayden" @(3, 5, 6) 1 "William"    
}

Describe "rank" {
  Context "Fixed Tests" {
    It "Should Pass Fixed Tests" {
      fixed
    } 
  }
}

# After, testing and fixed functions are in the BeforeAll, the tests are working :D
BeforeAll {
  . $PSCommandPath.Replace('.Tests.ps1', '.ps1')
  
  function testing($st, $we, $n, $expect) 
    {
        $ans = rank $st $we $n
        $ans | Should -Be $expect
    }

  function fixed()
    {
        testing "Addison,Jayden,Sofia,Michael,Andrew,Lily,Benjamin" @(4, 2, 1, 4, 3, 1, 2) 4 "Benjamin" 
        testing "Addison,Jayden,Sofia,Michael,Andrew,Lily,Benjamin" @(4, 2, 1, 4, 3, 1, 2) 8 "Not enough participants"
        testing "" @(4, 2, 1, 4, 3, 1, 2) 6 "No participants"
        testing "Addison,William,Jayden" @(3, 5, 6) 1 "William"    

    }
}

Describe "rank" {
  Context "Fixed Tests" {
    It "Should Pass Fixed Tests" {
      fixed
    } 
  }
}
```

Hope I helped with this case :)

**Comment by kazk** [comment]
@4500zenja1 Thanks! Approved.
